//! Read-only OFX facade readiness planner for the future AEX bridge.
//!
//! This example consumes local JSON contracts generated by the AEX readiness
//! flow. It does not import an OFX SDK, start an OFX host, open `.aex` files,
//! or issue worker render/describe requests.

use serde::{Deserialize, Serialize};
use std::collections::BTreeSet;
use std::error::Error;
use std::fs::OpenOptions;
use std::io::{ErrorKind, Write};
use std::path::{Path, PathBuf};

#[derive(Debug, Deserialize)]
struct OfxFacadeContract {
    #[serde(default)]
    status: String,
    #[serde(default)]
    route: OfxRoute,
    #[serde(default)]
    forbidden_paths: Vec<String>,
    #[serde(default)]
    current_supported_operations: Vec<String>,
    #[serde(default)]
    ofx_facade_review_gate: ContractOfxFacadeReviewGate,
}

#[derive(Debug, Default, Deserialize)]
struct ContractOfxFacadeReviewGate {
    #[serde(default)]
    status: String,
    #[serde(default)]
    approved: bool,
    #[serde(default)]
    may_point_to_broker: bool,
    #[serde(default)]
    may_issue_describe: bool,
    #[serde(default)]
    may_issue_render_png: bool,
    #[serde(default)]
    requires_separate_review_after_aex_loader_gate: bool,
    #[serde(default)]
    requires_capability_ids_subset_of_loader_gate: bool,
    #[serde(default)]
    requires_same_shared_gates: bool,
}

#[derive(Debug, Default, Deserialize)]
struct OfxRoute {
    #[serde(default)]
    aviutlas_to_aex_route: String,
    #[serde(default)]
    ofx_host_may_load_aex: bool,
    #[serde(default)]
    ofx_adapter_may_load_aex: bool,
    #[serde(default)]
    broker_may_load_aex: bool,
    #[serde(default)]
    worker_required: bool,
    #[serde(default)]
    worker_protocol: String,
    #[serde(default)]
    first_loader_owner: String,
}

#[derive(Debug, Deserialize)]
struct FixtureReviewGate {
    #[serde(default)]
    status: String,
    #[serde(default)]
    selected_fixture: Option<String>,
    #[serde(default)]
    approval: FixtureApproval,
    #[serde(default)]
    candidates: Vec<serde_json::Value>,
}

#[derive(Debug, Default, Deserialize)]
struct FixtureApproval {
    #[serde(default)]
    approved: bool,
    #[serde(default)]
    loader_enabled: bool,
    #[serde(default)]
    real_aex_load_enabled: bool,
    #[serde(default)]
    render_png_enabled: bool,
}

#[derive(Debug, Deserialize)]
struct LoaderGate {
    #[serde(default)]
    status: String,
    #[serde(default)]
    approved: bool,
    #[serde(default)]
    loader_enabled: bool,
    #[serde(default)]
    real_aex_load_enabled: bool,
    #[serde(default)]
    open_candidate_count: u32,
    #[serde(default)]
    entries: Vec<serde_json::Value>,
}

#[derive(Debug, Deserialize)]
struct CapabilityDraft {
    effect_id: String,
    #[serde(default)]
    display_name: String,
    #[serde(default)]
    load_status: String,
    #[serde(default)]
    broker_may_load_plugin: bool,
    #[serde(default)]
    current_supported_operations: Vec<String>,
    #[serde(default)]
    params_status: String,
    #[serde(default)]
    aex_worker: CapabilitySurface,
    #[serde(default)]
    ofx_facade: CapabilitySurface,
}

#[derive(Debug, Default, Deserialize)]
struct CapabilitySurface {
    #[serde(default)]
    supported: bool,
    #[serde(default)]
    status: String,
}

#[derive(Debug, Serialize)]
struct OfxFacadeReadinessReport {
    schema_version: u32,
    publication_status: String,
    status: String,
    contract_status: String,
    ofx_host_may_load_aex: bool,
    ofx_adapter_may_load_aex: bool,
    aviutlas_may_route_through_ofx_to_reach_aex: bool,
    broker_may_load_aex: bool,
    worker_required: bool,
    worker_protocol: String,
    first_loader_owner: String,
    fixture_gate: FixtureGateSummary,
    loader_gate: LoaderGateSummary,
    native_stage_plan_summary: NativeStagePlanSummary,
    loader_slice_review_summary: LoaderSliceReviewSummary,
    loader_approval_summary: LoaderApprovalSummary,
    aex_metadata_gate_summary: AexMetadataGateSummary,
    ofx_facade_review_gate: OfxFacadeReviewGateSummary,
    capability_count: usize,
    supported_capability_count: usize,
    current_supported_operations: Vec<String>,
    describe_exposure: String,
    render_png_exposure: String,
    entries: Vec<OfxFacadeCapabilityEntry>,
    forbidden_paths: Vec<String>,
    blocked_reasons: Vec<String>,
    notes: Vec<String>,
}

#[derive(Debug, Serialize)]
struct FixtureGateSummary {
    status: String,
    selected_fixture: Option<String>,
    approved: bool,
    loader_enabled: bool,
    real_aex_load_enabled: bool,
    render_png_enabled: bool,
    candidate_count: usize,
}

#[derive(Debug, Serialize)]
struct LoaderGateSummary {
    status: String,
    approved: bool,
    loader_enabled: bool,
    real_aex_load_enabled: bool,
    open_candidate_count: u32,
    entry_count: usize,
}

#[derive(Debug, Default, Deserialize)]
struct NativeStagePlanInput {
    #[serde(default)]
    status: String,
    #[serde(default)]
    native_load_performed: bool,
    #[serde(default)]
    broker_may_load_plugin: bool,
    #[serde(default)]
    selectors_executed: bool,
    #[serde(default)]
    render_performed: bool,
    #[serde(default)]
    worker_may_load_plugin: bool,
    #[serde(default)]
    ofx_may_route_to_loader: bool,
    #[serde(default)]
    promotion_gate: NativeStagePromotionGate,
    #[serde(default)]
    ticket_runtime_evidence_summary: NativeStageRuntimeEvidence,
    #[serde(default)]
    cleanroom_boundary_summary: Option<NativeStageCleanroomBoundary>,
    #[serde(default)]
    native_stage_order: Vec<NativeStageInput>,
}

#[derive(Debug, Default, Deserialize)]
struct NativeStageInput {
    #[serde(default)]
    status: String,
}

#[derive(Debug, Default, Deserialize)]
struct NativeStagePromotionGate {
    #[serde(default)]
    native_loader_calls_allowed: bool,
    #[serde(default)]
    worker_selector_calls_allowed: bool,
    #[serde(default)]
    worker_pixel_buffers_allowed: bool,
    #[serde(default)]
    ofx_facade_may_route_to_loader: bool,
}

#[derive(Debug, Default, Deserialize)]
struct NativeStageRuntimeEvidence {
    #[serde(default)]
    worker_identity_revalidation_required: Option<String>,
    #[serde(default)]
    worker_attestation_required: Option<String>,
    #[serde(default)]
    sandbox_preflight_required: Option<String>,
    #[serde(default)]
    job_object_required: Option<String>,
    #[serde(default)]
    handle_inheritance_required: Option<String>,
}

#[derive(Debug, Default, Deserialize)]
struct NativeStageCleanroomBoundary {
    #[serde(default)]
    native_loader_calls_allowed: Option<bool>,
    #[serde(default)]
    adobe_sdk_headers_allowed: Option<bool>,
    #[serde(default)]
    abi_generator_allowed: Option<bool>,
    #[serde(default)]
    third_party_effect_host_crate_allowed: Option<bool>,
    #[serde(default)]
    third_party_pipl_crate_allowed: Option<bool>,
    #[serde(default)]
    reuse_existing_aviutl_dynamic_loader_for_aex_allowed: Option<bool>,
    #[serde(default)]
    pf_names_are_planning_labels_only: Option<bool>,
    #[serde(default)]
    metadata_labels_do_not_define_abi: Option<bool>,
}

#[derive(Debug, Serialize)]
struct NativeStagePlanSummary {
    provided: bool,
    status: Option<String>,
    no_load_stage_plan_ready: bool,
    worker_runtime_evidence_ready: bool,
    cleanroom_boundary_provided: bool,
    cleanroom_boundary_no_loader_or_sdk: bool,
    selector_execution_blocked: bool,
    render_blocked: bool,
    ofx_route_blocked: bool,
    native_stage_count: usize,
    planned_not_run_count: usize,
    input_contains_forbidden_tokens: bool,
}

#[derive(Debug, Serialize)]
struct LoaderSliceReviewSummary {
    provided: bool,
    status: Option<String>,
    ready_for_manual_loader_slice_review_no_load: bool,
    loader_slice_approved: bool,
    loader_enabled: bool,
    real_aex_load_enabled: bool,
    native_loader_calls_allowed: bool,
    broker_may_load_aex: bool,
    worker_may_load_plugin: bool,
    render_performed: bool,
    ofx_route_allowed: bool,
    input_contains_forbidden_tokens: bool,
}

#[derive(Debug, Default, Deserialize)]
struct LoaderSliceReviewInput {
    #[serde(default)]
    status: String,
    #[serde(default)]
    loader_slice_approved: bool,
    #[serde(default)]
    loader_enabled: bool,
    #[serde(default)]
    real_aex_load_enabled: bool,
    #[serde(default)]
    native_loader_calls_allowed: bool,
    #[serde(default)]
    broker_may_load_aex: bool,
    #[serde(default)]
    worker_may_load_plugin: bool,
    #[serde(default)]
    render_performed: bool,
    #[serde(default)]
    ofx_route_allowed: bool,
}

#[derive(Debug, Serialize)]
struct LoaderApprovalSummary {
    provided: bool,
    validation_status: Option<String>,
    approval_accepted: bool,
    loader_review_approved: bool,
    loader_slice_review_packet_checked: bool,
    loader_slice_review_packet_status: Option<String>,
    loader_slice_review_packet_checksum_algorithm: Option<String>,
    native_load_performed: bool,
    loader_enabled: bool,
    real_aex_load_enabled: bool,
    native_loader_calls_allowed: bool,
    worker_may_load_plugin: bool,
    broker_may_load_aex: bool,
    render_performed: bool,
    ofx_route_allowed: bool,
    receipt_allows_separate_loader_implementation_review: bool,
    receipt_allows_native_aex_load: bool,
    receipt_allows_worker_plugin_load: bool,
    receipt_allows_render_png: bool,
    receipt_allows_ofx_route: bool,
    blocked_reason_count: usize,
    input_contains_forbidden_tokens: bool,
}

#[derive(Debug, Default, Deserialize)]
struct LoaderApprovalInput {
    #[serde(default)]
    validation_status: String,
    #[serde(default)]
    approval_accepted: bool,
    #[serde(default)]
    loader_review_approved: bool,
    #[serde(default)]
    native_load_performed: bool,
    #[serde(default)]
    loader_enabled: bool,
    #[serde(default)]
    real_aex_load_enabled: bool,
    #[serde(default)]
    native_loader_calls_allowed: bool,
    #[serde(default)]
    worker_may_load_plugin: bool,
    #[serde(default)]
    broker_may_load_aex: bool,
    #[serde(default)]
    render_performed: bool,
    #[serde(default)]
    ofx_route_allowed: bool,
    #[serde(default)]
    input_contains_forbidden_tokens: bool,
    #[serde(default)]
    loader_slice_review_packet_checked: bool,
    #[serde(default)]
    loader_slice_review_packet_status: String,
    #[serde(default)]
    loader_slice_review_packet_checksum_algorithm: String,
    #[serde(default)]
    receipt_allows_separate_loader_implementation_review: bool,
    #[serde(default)]
    receipt_allows_native_aex_load: bool,
    #[serde(default)]
    receipt_allows_worker_plugin_load: bool,
    #[serde(default)]
    receipt_allows_render_png: bool,
    #[serde(default)]
    receipt_allows_ofx_route: bool,
    #[serde(default)]
    blocked_reasons: Vec<serde_json::Value>,
}

#[derive(Debug, Serialize)]
struct AexMetadataGateSummary {
    provided: bool,
    status: Option<String>,
    report_kind: Option<String>,
    publication_status: Option<String>,
    ready_for_ofx_review_no_load: bool,
    native_load_performed: bool,
    render_performed: bool,
    aex_loaded: bool,
    worker_started: bool,
    broker_load_or_render_allowed: bool,
    ofx_route_allowed: bool,
    ae_invoked: bool,
    private_payload_copied: bool,
    fixture_gate_status: Option<String>,
    fixture_selected: bool,
    fixture_approval_approved: bool,
    fixture_loader_enabled: bool,
    fixture_real_aex_load_enabled: bool,
    fixture_render_png_enabled: bool,
    loader_gate_status: Option<String>,
    loader_gate_approved: bool,
    loader_gate_loader_enabled: bool,
    loader_gate_real_aex_load_enabled: bool,
    loader_gate_open_candidate_count: u32,
    identity_smoke_status: Option<String>,
    identity_smoke_aex_loaded: bool,
    identity_smoke_ofx_route_invoked: bool,
    identity_smoke_aex_render_correctness_evidence: bool,
    ofx_contract_status: Option<String>,
    ofx_contract_review_approved: bool,
    ofx_contract_ofx_host_may_load_aex: bool,
    ofx_contract_ofx_adapter_may_load_aex: bool,
    ofx_contract_broker_may_load_aex: bool,
    blocked_reason_count: usize,
    input_contains_forbidden_tokens: bool,
}

#[derive(Debug, Default, Deserialize)]
struct AexMetadataGateInput {
    #[serde(default)]
    schema_version: u32,
    #[serde(default)]
    report_kind: String,
    #[serde(default)]
    publication_status: String,
    #[serde(default)]
    status: String,
    #[serde(default)]
    native_load_performed: bool,
    #[serde(default)]
    render_performed: bool,
    #[serde(default)]
    aex_loaded: bool,
    #[serde(default)]
    worker_started: bool,
    #[serde(default)]
    broker_load_or_render_allowed: bool,
    #[serde(default)]
    ofx_route_allowed: bool,
    #[serde(default)]
    ae_invoked: bool,
    #[serde(default)]
    private_payload_copied: bool,
    #[serde(default)]
    fixture_gate_summary: AexMetadataFixtureGateSummary,
    #[serde(default)]
    loader_gate_summary: AexMetadataLoaderGateSummary,
    #[serde(default)]
    identity_smoke_summary: AexMetadataIdentitySmokeSummary,
    #[serde(default)]
    ofx_contract_summary: AexMetadataOfxContractSummary,
    #[serde(default)]
    blocked_reasons: Vec<serde_json::Value>,
}

#[derive(Debug, Default, Deserialize)]
struct AexMetadataFixtureGateSummary {
    #[serde(default)]
    status: String,
    #[serde(default)]
    selected_fixture_present: bool,
    #[serde(default)]
    approval_approved: bool,
    #[serde(default)]
    approval_loader_enabled: bool,
    #[serde(default)]
    approval_real_aex_load_enabled: bool,
    #[serde(default)]
    approval_render_png_enabled: bool,
}

#[derive(Debug, Default, Deserialize)]
struct AexMetadataLoaderGateSummary {
    #[serde(default)]
    status: String,
    #[serde(default)]
    approved: bool,
    #[serde(default)]
    loader_enabled: bool,
    #[serde(default)]
    real_aex_load_enabled: bool,
    #[serde(default)]
    open_candidate_count: u32,
}

#[derive(Debug, Default, Deserialize)]
struct AexMetadataIdentitySmokeSummary {
    #[serde(default)]
    status: String,
    #[serde(default)]
    native_load_performed: bool,
    #[serde(default)]
    render_performed: bool,
    #[serde(default)]
    aex_loaded: bool,
    #[serde(default)]
    worker_started: bool,
    #[serde(default)]
    ofx_route_invoked: bool,
    #[serde(default)]
    ae_invoked: bool,
    #[serde(default)]
    private_payload_copied: bool,
    #[serde(default)]
    aex_render_correctness_evidence: bool,
}

#[derive(Debug, Default, Deserialize)]
struct AexMetadataOfxContractSummary {
    #[serde(default)]
    status: String,
    #[serde(default)]
    ofx_host_may_load_aex: bool,
    #[serde(default)]
    ofx_adapter_may_load_aex: bool,
    #[serde(default)]
    broker_may_load_aex: bool,
    #[serde(default)]
    review_approved: bool,
    #[serde(default)]
    may_point_to_broker: bool,
    #[serde(default)]
    may_issue_describe: bool,
    #[serde(default)]
    may_issue_render_png: bool,
}

#[derive(Debug, Serialize)]
struct OfxFacadeReviewGateSummary {
    status: String,
    approved: bool,
    may_point_to_broker: bool,
    may_issue_describe: bool,
    may_issue_render_png: bool,
    requires_separate_review_after_aex_loader_gate: bool,
    requires_capability_ids_subset_of_loader_gate: bool,
    requires_same_shared_gates: bool,
}

#[derive(Debug, Serialize)]
struct OfxFacadeCapabilityEntry {
    effect_id: String,
    display_name: String,
    load_status: String,
    broker_may_load_plugin: bool,
    current_supported_operations: Vec<String>,
    params_status: String,
    aex_worker_status: String,
    ofx_facade_status: String,
    ofx_facade_supported: bool,
    exposure_status: String,
}

pub fn plan_ofx_facade_readiness_json(
    contract_json: &str,
    fixture_gate_json: &str,
    loader_gate_json: &str,
    capability_jsons: &[&str],
) -> Result<String, Box<dyn Error>> {
    plan_ofx_facade_readiness_json_with_native_stage_plan(
        contract_json,
        fixture_gate_json,
        loader_gate_json,
        None,
        capability_jsons,
    )
}

pub fn plan_ofx_facade_readiness_json_with_native_stage_plan(
    contract_json: &str,
    fixture_gate_json: &str,
    loader_gate_json: &str,
    native_stage_plan_json: Option<&str>,
    capability_jsons: &[&str],
) -> Result<String, Box<dyn Error>> {
    plan_ofx_facade_readiness_json_with_native_stage_plan_and_loader_slice_review(
        contract_json,
        fixture_gate_json,
        loader_gate_json,
        native_stage_plan_json,
        None,
        capability_jsons,
    )
}

pub fn plan_ofx_facade_readiness_json_with_native_stage_plan_and_loader_slice_review(
    contract_json: &str,
    fixture_gate_json: &str,
    loader_gate_json: &str,
    native_stage_plan_json: Option<&str>,
    loader_slice_review_json: Option<&str>,
    capability_jsons: &[&str],
) -> Result<String, Box<dyn Error>> {
    plan_ofx_facade_readiness_json_with_native_stage_plan_and_loader_evidence(
        contract_json,
        fixture_gate_json,
        loader_gate_json,
        native_stage_plan_json,
        loader_slice_review_json,
        None,
        capability_jsons,
    )
}

pub fn plan_ofx_facade_readiness_json_with_native_stage_plan_and_loader_evidence(
    contract_json: &str,
    fixture_gate_json: &str,
    loader_gate_json: &str,
    native_stage_plan_json: Option<&str>,
    loader_slice_review_json: Option<&str>,
    loader_approval_report_json: Option<&str>,
    capability_jsons: &[&str],
) -> Result<String, Box<dyn Error>> {
    plan_ofx_facade_readiness_json_with_all_evidence(OfxFacadeReadinessJsonInputs {
        contract_json,
        fixture_gate_json,
        loader_gate_json,
        native_stage_plan_json,
        loader_slice_review_json,
        loader_approval_report_json,
        aex_metadata_gate_report_json: None,
        capability_jsons,
    })
}

pub struct OfxFacadeReadinessJsonInputs<'a> {
    pub contract_json: &'a str,
    pub fixture_gate_json: &'a str,
    pub loader_gate_json: &'a str,
    pub native_stage_plan_json: Option<&'a str>,
    pub loader_slice_review_json: Option<&'a str>,
    pub loader_approval_report_json: Option<&'a str>,
    pub aex_metadata_gate_report_json: Option<&'a str>,
    pub capability_jsons: &'a [&'a str],
}

struct OfxFacadeReadinessInputs {
    contract: OfxFacadeContract,
    fixture_gate: FixtureReviewGate,
    loader_gate: LoaderGate,
    native_stage_plan: Option<NativeStagePlanSummary>,
    loader_slice_review: Option<LoaderSliceReviewSummary>,
    loader_approval: Option<LoaderApprovalSummary>,
    aex_metadata_gate: Option<AexMetadataGateSummary>,
    capabilities: Vec<CapabilityDraft>,
}

pub fn plan_ofx_facade_readiness_json_with_all_evidence(
    inputs: OfxFacadeReadinessJsonInputs<'_>,
) -> Result<String, Box<dyn Error>> {
    let contract: OfxFacadeContract = serde_json::from_str(inputs.contract_json)?;
    let fixture_gate: FixtureReviewGate = serde_json::from_str(inputs.fixture_gate_json)?;
    let loader_gate: LoaderGate = serde_json::from_str(inputs.loader_gate_json)?;
    let native_stage_plan = inputs
        .native_stage_plan_json
        .map(parse_native_stage_plan)
        .transpose()?;
    let loader_slice_review = inputs
        .loader_slice_review_json
        .map(parse_loader_slice_review_packet)
        .transpose()?;
    let loader_approval = inputs
        .loader_approval_report_json
        .map(parse_loader_approval_report)
        .transpose()?;
    let aex_metadata_gate = inputs
        .aex_metadata_gate_report_json
        .map(parse_aex_metadata_gate_report)
        .transpose()?;
    let capabilities = inputs
        .capability_jsons
        .iter()
        .map(|json| serde_json::from_str::<CapabilityDraft>(json))
        .collect::<Result<Vec<_>, _>>()?;
    let report = plan_ofx_facade_readiness(OfxFacadeReadinessInputs {
        contract,
        fixture_gate,
        loader_gate,
        native_stage_plan,
        loader_slice_review,
        loader_approval,
        aex_metadata_gate,
        capabilities,
    });
    Ok(serde_json::to_string_pretty(&report)?)
}

fn plan_ofx_facade_readiness(inputs: OfxFacadeReadinessInputs) -> OfxFacadeReadinessReport {
    let OfxFacadeReadinessInputs {
        contract,
        fixture_gate,
        loader_gate,
        native_stage_plan,
        loader_slice_review,
        loader_approval,
        aex_metadata_gate,
        capabilities,
    } = inputs;
    let mut blocked_reasons = Vec::new();
    let native_stage_plan = native_stage_plan.unwrap_or_else(native_stage_plan_not_provided);
    let loader_slice_review =
        loader_slice_review.unwrap_or_else(loader_slice_review_packet_not_provided);
    let loader_approval = loader_approval.unwrap_or_else(loader_approval_report_not_provided);
    let aex_metadata_gate = aex_metadata_gate.unwrap_or_else(aex_metadata_gate_report_not_provided);

    if contract.status != "deferred-contract-only" {
        blocked_reasons.push("OFX facade contract is not deferred-contract-only".to_string());
    }
    if contract.route.ofx_host_may_load_aex {
        blocked_reasons.push("OFX host route claims it may load .aex".to_string());
    }
    if contract.route.ofx_adapter_may_load_aex {
        blocked_reasons.push("OFX adapter route claims it may load .aex".to_string());
    }
    if contract.route.broker_may_load_aex {
        blocked_reasons.push("broker route claims it may load .aex".to_string());
    }
    if contract.route.aviutlas_to_aex_route != "direct-aex-broker-not-ofx" {
        blocked_reasons.push("AviUtlas AEX route is not direct broker first".to_string());
    }
    if contract.ofx_facade_review_gate.approved
        || contract.ofx_facade_review_gate.may_point_to_broker
        || contract.ofx_facade_review_gate.may_issue_describe
        || contract.ofx_facade_review_gate.may_issue_render_png
    {
        blocked_reasons
            .push("OFX facade review gate is open before AEX worker support exists".to_string());
    }
    if loader_gate.approved || loader_gate.loader_enabled || loader_gate.real_aex_load_enabled {
        blocked_reasons
            .push("AEX loader gate is open; OFX readiness must be reviewed separately".to_string());
    }
    if loader_gate.open_candidate_count > 0 && !contract.ofx_facade_review_gate.approved {
        blocked_reasons.push(
            "OFX facade review is still required before pointing at the AEX broker".to_string(),
        );
    }
    if fixture_gate.approval.loader_enabled
        || fixture_gate.approval.real_aex_load_enabled
        || fixture_gate.approval.render_png_enabled
    {
        blocked_reasons
            .push("fixture gate enables loader or render before OFX facade review".to_string());
    }
    if native_stage_plan.provided && !native_stage_plan_ready_for_ofx_review(&native_stage_plan) {
        blocked_reasons.push(
            "native stage plan does not preserve no-load/runtime/cleanroom evidence for OFX facade review".to_string(),
        );
    }
    if loader_slice_review.provided
        && !loader_slice_review_ready_for_ofx_review(&loader_slice_review)
    {
        blocked_reasons.push(
            "loader slice review packet does not preserve sanitized no-load evidence for OFX facade review".to_string(),
        );
    }
    if loader_approval.provided && !loader_approval_ready_for_ofx_review(&loader_approval) {
        blocked_reasons.push(
            "loader approval validation report does not preserve review-only no-load evidence for OFX facade review".to_string(),
        );
    }
    if aex_metadata_gate.provided && !aex_metadata_gate_ready_for_ofx_review(&aex_metadata_gate) {
        blocked_reasons.push(
            "AEX metadata gate report does not preserve no-load/deferred evidence for OFX facade review".to_string(),
        );
    }

    let mut supported_capability_count = 0;
    let loader_effect_ids = loader_gate
        .entries
        .iter()
        .filter_map(|entry| entry.get("effect_id").and_then(|value| value.as_str()))
        .collect::<BTreeSet<_>>();
    let entries = capabilities
        .into_iter()
        .map(|capability| {
            if contract
                .ofx_facade_review_gate
                .requires_capability_ids_subset_of_loader_gate
                && !loader_effect_ids.contains(capability.effect_id.as_str())
            {
                blocked_reasons.push(format!(
                    "capability effect_id {} is not present in loader gate entries",
                    capability.effect_id
                ));
            }
            if capability.ofx_facade.supported {
                supported_capability_count += 1;
                blocked_reasons.push(
                    "capability says OFX facade is supported before loader approval".to_string(),
                );
            }
            if capability.broker_may_load_plugin {
                blocked_reasons.push(
                    "capability says broker may load plugin before OFX facade review".to_string(),
                );
            }
            if !capability.current_supported_operations.is_empty() {
                blocked_reasons.push(
                    "capability exposes operations before OFX facade is implemented".to_string(),
                );
            }
            OfxFacadeCapabilityEntry {
                effect_id: capability.effect_id,
                display_name: capability.display_name,
                load_status: capability.load_status,
                broker_may_load_plugin: capability.broker_may_load_plugin,
                current_supported_operations: capability.current_supported_operations,
                params_status: capability.params_status,
                aex_worker_status: capability.aex_worker.status,
                ofx_facade_status: capability.ofx_facade.status,
                ofx_facade_supported: capability.ofx_facade.supported,
                exposure_status: "deferred_same_aex_worker_gate".to_string(),
            }
        })
        .collect::<Vec<_>>();

    let report_status = if blocked_reasons.is_empty() {
        "deferred_contract_only"
    } else {
        "blocked_contract_mismatch"
    };
    let describe_exposure = if entries.is_empty() {
        "blocked_no_capabilities"
    } else {
        "metadata_only_no_worker_describe"
    };
    let render_png_exposure = if loader_gate.loader_enabled
        || loader_gate.real_aex_load_enabled
        || loader_gate.open_candidate_count > 0
        || loader_slice_review.provided
        || loader_approval.provided
    {
        "blocked_pending_separate_ofx_review"
    } else {
        "blocked_loader_gate_closed"
    };

    OfxFacadeReadinessReport {
        schema_version: 1,
        publication_status: "local-only".to_string(),
        status: report_status.to_string(),
        contract_status: contract.status,
        ofx_host_may_load_aex: false,
        ofx_adapter_may_load_aex: false,
        aviutlas_may_route_through_ofx_to_reach_aex: false,
        broker_may_load_aex: false,
        worker_required: contract.route.worker_required,
        worker_protocol: contract.route.worker_protocol,
        first_loader_owner: contract.route.first_loader_owner,
        fixture_gate: FixtureGateSummary {
            status: fixture_gate.status,
            selected_fixture: fixture_gate.selected_fixture,
            approved: fixture_gate.approval.approved,
            loader_enabled: fixture_gate.approval.loader_enabled,
            real_aex_load_enabled: fixture_gate.approval.real_aex_load_enabled,
            render_png_enabled: fixture_gate.approval.render_png_enabled,
            candidate_count: fixture_gate.candidates.len(),
        },
        loader_gate: LoaderGateSummary {
            status: loader_gate.status,
            approved: loader_gate.approved,
            loader_enabled: loader_gate.loader_enabled,
            real_aex_load_enabled: loader_gate.real_aex_load_enabled,
            open_candidate_count: loader_gate.open_candidate_count,
            entry_count: loader_gate.entries.len(),
        },
        native_stage_plan_summary: native_stage_plan,
        loader_slice_review_summary: loader_slice_review,
        loader_approval_summary: loader_approval,
        aex_metadata_gate_summary: aex_metadata_gate,
        ofx_facade_review_gate: OfxFacadeReviewGateSummary {
            status: contract.ofx_facade_review_gate.status,
            approved: contract.ofx_facade_review_gate.approved,
            may_point_to_broker: contract.ofx_facade_review_gate.may_point_to_broker,
            may_issue_describe: contract.ofx_facade_review_gate.may_issue_describe,
            may_issue_render_png: contract.ofx_facade_review_gate.may_issue_render_png,
            requires_separate_review_after_aex_loader_gate: contract
                .ofx_facade_review_gate
                .requires_separate_review_after_aex_loader_gate,
            requires_capability_ids_subset_of_loader_gate: contract
                .ofx_facade_review_gate
                .requires_capability_ids_subset_of_loader_gate,
            requires_same_shared_gates: contract.ofx_facade_review_gate.requires_same_shared_gates,
        },
        capability_count: entries.len(),
        supported_capability_count,
        current_supported_operations: contract.current_supported_operations,
        describe_exposure: describe_exposure.to_string(),
        render_png_exposure: render_png_exposure.to_string(),
        entries,
        forbidden_paths: contract.forbidden_paths,
        blocked_reasons,
        notes: vec![
            "OFX facade readiness reads JSON metadata only.".to_string(),
            "No OFX SDK, OFX host process, .aex load, worker describe, or render is used.".to_string(),
            "AviUtlas must keep the direct AEX broker path as the first loader route.".to_string(),
            "OFX may become a facade only after the same AEX worker loader gate is opened and reviewed separately.".to_string(),
        ],
    }
}

fn parse_native_stage_plan(text: &str) -> Result<NativeStagePlanSummary, serde_json::Error> {
    let input_contains_forbidden_tokens = string_contains_forbidden_tokens(text);
    let input = serde_json::from_str::<NativeStagePlanInput>(text)?;
    let native_stage_count = input.native_stage_order.len();
    let planned_not_run_count = input
        .native_stage_order
        .iter()
        .filter(|stage| stage.status == "planned_not_run")
        .count();
    let worker_runtime_evidence_ready =
        native_stage_runtime_evidence_ready(&input.ticket_runtime_evidence_summary);
    let cleanroom_boundary_no_loader_or_sdk = input
        .cleanroom_boundary_summary
        .as_ref()
        .is_some_and(native_stage_cleanroom_boundary_no_loader_or_sdk);
    let selector_execution_blocked =
        !input.selectors_executed && !input.promotion_gate.worker_selector_calls_allowed;
    let render_blocked =
        !input.render_performed && !input.promotion_gate.worker_pixel_buffers_allowed;
    let ofx_route_blocked =
        !input.ofx_may_route_to_loader && !input.promotion_gate.ofx_facade_may_route_to_loader;
    let status = if input_contains_forbidden_tokens {
        None
    } else {
        non_empty_string(input.status.clone())
    };
    let no_load_stage_plan_ready = !input_contains_forbidden_tokens
        && status.as_deref() == Some("planned_native_stage_contract_no_load")
        && !input.native_load_performed
        && !input.broker_may_load_plugin
        && !input.worker_may_load_plugin
        && !input.promotion_gate.native_loader_calls_allowed
        && native_stage_count > 0
        && native_stage_count == planned_not_run_count
        && selector_execution_blocked
        && render_blocked
        && ofx_route_blocked;

    Ok(NativeStagePlanSummary {
        provided: true,
        status,
        no_load_stage_plan_ready,
        worker_runtime_evidence_ready,
        cleanroom_boundary_provided: input.cleanroom_boundary_summary.is_some(),
        cleanroom_boundary_no_loader_or_sdk,
        selector_execution_blocked,
        render_blocked,
        ofx_route_blocked,
        native_stage_count,
        planned_not_run_count,
        input_contains_forbidden_tokens,
    })
}

fn native_stage_plan_not_provided() -> NativeStagePlanSummary {
    NativeStagePlanSummary {
        provided: false,
        status: None,
        no_load_stage_plan_ready: false,
        worker_runtime_evidence_ready: false,
        cleanroom_boundary_provided: false,
        cleanroom_boundary_no_loader_or_sdk: false,
        selector_execution_blocked: false,
        render_blocked: false,
        ofx_route_blocked: false,
        native_stage_count: 0,
        planned_not_run_count: 0,
        input_contains_forbidden_tokens: false,
    }
}

fn parse_loader_slice_review_packet(
    text: &str,
) -> Result<LoaderSliceReviewSummary, serde_json::Error> {
    let input_contains_forbidden_tokens = loader_slice_review_contains_forbidden_tokens(text);
    let input = serde_json::from_str::<LoaderSliceReviewInput>(text)?;
    let status = if input_contains_forbidden_tokens {
        None
    } else {
        non_empty_string(input.status.clone())
    };
    let ready_for_manual_loader_slice_review_no_load = status.as_deref()
        == Some("ready_for_manual_loader_slice_review_no_load")
        && !input.loader_slice_approved
        && !input.loader_enabled
        && !input.real_aex_load_enabled
        && !input.native_loader_calls_allowed
        && !input.broker_may_load_aex
        && !input.worker_may_load_plugin
        && !input.render_performed
        && !input.ofx_route_allowed
        && !input_contains_forbidden_tokens;

    Ok(LoaderSliceReviewSummary {
        provided: true,
        status,
        ready_for_manual_loader_slice_review_no_load,
        loader_slice_approved: input.loader_slice_approved,
        loader_enabled: input.loader_enabled,
        real_aex_load_enabled: input.real_aex_load_enabled,
        native_loader_calls_allowed: input.native_loader_calls_allowed,
        broker_may_load_aex: input.broker_may_load_aex,
        worker_may_load_plugin: input.worker_may_load_plugin,
        render_performed: input.render_performed,
        ofx_route_allowed: input.ofx_route_allowed,
        input_contains_forbidden_tokens,
    })
}

fn loader_slice_review_packet_not_provided() -> LoaderSliceReviewSummary {
    LoaderSliceReviewSummary {
        provided: false,
        status: None,
        ready_for_manual_loader_slice_review_no_load: false,
        loader_slice_approved: false,
        loader_enabled: false,
        real_aex_load_enabled: false,
        native_loader_calls_allowed: false,
        broker_may_load_aex: false,
        worker_may_load_plugin: false,
        render_performed: false,
        ofx_route_allowed: false,
        input_contains_forbidden_tokens: false,
    }
}

fn parse_loader_approval_report(text: &str) -> Result<LoaderApprovalSummary, serde_json::Error> {
    let input_contains_forbidden_tokens = loader_approval_contains_forbidden_tokens(text);
    let input = serde_json::from_str::<LoaderApprovalInput>(text)?;
    let validation_status = if input_contains_forbidden_tokens {
        None
    } else {
        non_empty_string(input.validation_status.clone())
    };
    let loader_slice_review_packet_status = if input_contains_forbidden_tokens {
        None
    } else {
        non_empty_string(input.loader_slice_review_packet_status.clone())
    };
    let loader_slice_review_packet_checksum_algorithm = if input_contains_forbidden_tokens {
        None
    } else {
        non_empty_string(input.loader_slice_review_packet_checksum_algorithm.clone())
    };

    Ok(LoaderApprovalSummary {
        provided: true,
        validation_status,
        approval_accepted: input.approval_accepted,
        loader_review_approved: input.loader_review_approved,
        loader_slice_review_packet_checked: input.loader_slice_review_packet_checked,
        loader_slice_review_packet_status,
        loader_slice_review_packet_checksum_algorithm,
        native_load_performed: input.native_load_performed,
        loader_enabled: input.loader_enabled,
        real_aex_load_enabled: input.real_aex_load_enabled,
        native_loader_calls_allowed: input.native_loader_calls_allowed,
        worker_may_load_plugin: input.worker_may_load_plugin,
        broker_may_load_aex: input.broker_may_load_aex,
        render_performed: input.render_performed,
        ofx_route_allowed: input.ofx_route_allowed,
        receipt_allows_separate_loader_implementation_review: input
            .receipt_allows_separate_loader_implementation_review,
        receipt_allows_native_aex_load: input.receipt_allows_native_aex_load,
        receipt_allows_worker_plugin_load: input.receipt_allows_worker_plugin_load,
        receipt_allows_render_png: input.receipt_allows_render_png,
        receipt_allows_ofx_route: input.receipt_allows_ofx_route,
        blocked_reason_count: input.blocked_reasons.len(),
        input_contains_forbidden_tokens: input_contains_forbidden_tokens
            || input.input_contains_forbidden_tokens,
    })
}

fn loader_approval_report_not_provided() -> LoaderApprovalSummary {
    LoaderApprovalSummary {
        provided: false,
        validation_status: None,
        approval_accepted: false,
        loader_review_approved: false,
        loader_slice_review_packet_checked: false,
        loader_slice_review_packet_status: None,
        loader_slice_review_packet_checksum_algorithm: None,
        native_load_performed: false,
        loader_enabled: false,
        real_aex_load_enabled: false,
        native_loader_calls_allowed: false,
        worker_may_load_plugin: false,
        broker_may_load_aex: false,
        render_performed: false,
        ofx_route_allowed: false,
        receipt_allows_separate_loader_implementation_review: false,
        receipt_allows_native_aex_load: false,
        receipt_allows_worker_plugin_load: false,
        receipt_allows_render_png: false,
        receipt_allows_ofx_route: false,
        blocked_reason_count: 0,
        input_contains_forbidden_tokens: false,
    }
}

fn parse_aex_metadata_gate_report(text: &str) -> Result<AexMetadataGateSummary, serde_json::Error> {
    let input_contains_forbidden_tokens = aex_metadata_gate_contains_forbidden_tokens(text);
    let input = serde_json::from_str::<AexMetadataGateInput>(text)?;
    let status = sanitized_non_empty_string(input.status.clone(), input_contains_forbidden_tokens);
    let report_kind =
        sanitized_non_empty_string(input.report_kind.clone(), input_contains_forbidden_tokens);
    let publication_status = sanitized_non_empty_string(
        input.publication_status.clone(),
        input_contains_forbidden_tokens,
    );
    let fixture_gate_status = sanitized_non_empty_string(
        input.fixture_gate_summary.status.clone(),
        input_contains_forbidden_tokens,
    );
    let loader_gate_status = sanitized_non_empty_string(
        input.loader_gate_summary.status.clone(),
        input_contains_forbidden_tokens,
    );
    let identity_smoke_status = sanitized_non_empty_string(
        input.identity_smoke_summary.status.clone(),
        input_contains_forbidden_tokens,
    );
    let ofx_contract_status = sanitized_non_empty_string(
        input.ofx_contract_summary.status.clone(),
        input_contains_forbidden_tokens,
    );
    let fixture_gate_closed = input.fixture_gate_summary.status == "review_queue_not_approved"
        && !input.fixture_gate_summary.selected_fixture_present
        && !input.fixture_gate_summary.approval_approved
        && !input.fixture_gate_summary.approval_loader_enabled
        && !input.fixture_gate_summary.approval_real_aex_load_enabled
        && !input.fixture_gate_summary.approval_render_png_enabled;
    let loader_gate_closed = input.loader_gate_summary.status == "loader_gate_not_opened"
        && !input.loader_gate_summary.approved
        && !input.loader_gate_summary.loader_enabled
        && !input.loader_gate_summary.real_aex_load_enabled
        && input.loader_gate_summary.open_candidate_count == 0;
    let identity_smoke_no_load = input.identity_smoke_summary.status
        == "fixture_identity_smoke_ready_no_load"
        && !input.identity_smoke_summary.native_load_performed
        && !input.identity_smoke_summary.render_performed
        && !input.identity_smoke_summary.aex_loaded
        && !input.identity_smoke_summary.worker_started
        && !input.identity_smoke_summary.ofx_route_invoked
        && !input.identity_smoke_summary.ae_invoked
        && !input.identity_smoke_summary.private_payload_copied
        && !input.identity_smoke_summary.aex_render_correctness_evidence;
    let ofx_contract_deferred = input.ofx_contract_summary.status == "deferred-contract-only"
        && !input.ofx_contract_summary.ofx_host_may_load_aex
        && !input.ofx_contract_summary.ofx_adapter_may_load_aex
        && !input.ofx_contract_summary.broker_may_load_aex
        && !input.ofx_contract_summary.review_approved
        && !input.ofx_contract_summary.may_point_to_broker
        && !input.ofx_contract_summary.may_issue_describe
        && !input.ofx_contract_summary.may_issue_render_png;
    let top_level_no_load = !input.native_load_performed
        && !input.render_performed
        && !input.aex_loaded
        && !input.worker_started
        && !input.broker_load_or_render_allowed
        && !input.ofx_route_allowed
        && !input.ae_invoked
        && !input.private_payload_copied;
    let ready_for_ofx_review_no_load = !input_contains_forbidden_tokens
        && input.schema_version == 1
        && input.report_kind == "aex_metadata_gate_integration"
        && input.publication_status == "local-only"
        && input.status == "aex_metadata_gate_ready_no_load"
        && top_level_no_load
        && fixture_gate_closed
        && loader_gate_closed
        && identity_smoke_no_load
        && ofx_contract_deferred
        && input.blocked_reasons.is_empty();

    Ok(AexMetadataGateSummary {
        provided: true,
        status,
        report_kind,
        publication_status,
        ready_for_ofx_review_no_load,
        native_load_performed: input.native_load_performed,
        render_performed: input.render_performed,
        aex_loaded: input.aex_loaded,
        worker_started: input.worker_started,
        broker_load_or_render_allowed: input.broker_load_or_render_allowed,
        ofx_route_allowed: input.ofx_route_allowed,
        ae_invoked: input.ae_invoked,
        private_payload_copied: input.private_payload_copied,
        fixture_gate_status,
        fixture_selected: input.fixture_gate_summary.selected_fixture_present,
        fixture_approval_approved: input.fixture_gate_summary.approval_approved,
        fixture_loader_enabled: input.fixture_gate_summary.approval_loader_enabled,
        fixture_real_aex_load_enabled: input.fixture_gate_summary.approval_real_aex_load_enabled,
        fixture_render_png_enabled: input.fixture_gate_summary.approval_render_png_enabled,
        loader_gate_status,
        loader_gate_approved: input.loader_gate_summary.approved,
        loader_gate_loader_enabled: input.loader_gate_summary.loader_enabled,
        loader_gate_real_aex_load_enabled: input.loader_gate_summary.real_aex_load_enabled,
        loader_gate_open_candidate_count: input.loader_gate_summary.open_candidate_count,
        identity_smoke_status,
        identity_smoke_aex_loaded: input.identity_smoke_summary.aex_loaded,
        identity_smoke_ofx_route_invoked: input.identity_smoke_summary.ofx_route_invoked,
        identity_smoke_aex_render_correctness_evidence: input
            .identity_smoke_summary
            .aex_render_correctness_evidence,
        ofx_contract_status,
        ofx_contract_review_approved: input.ofx_contract_summary.review_approved,
        ofx_contract_ofx_host_may_load_aex: input.ofx_contract_summary.ofx_host_may_load_aex,
        ofx_contract_ofx_adapter_may_load_aex: input.ofx_contract_summary.ofx_adapter_may_load_aex,
        ofx_contract_broker_may_load_aex: input.ofx_contract_summary.broker_may_load_aex,
        blocked_reason_count: input.blocked_reasons.len(),
        input_contains_forbidden_tokens,
    })
}

fn aex_metadata_gate_report_not_provided() -> AexMetadataGateSummary {
    AexMetadataGateSummary {
        provided: false,
        status: None,
        report_kind: None,
        publication_status: None,
        ready_for_ofx_review_no_load: false,
        native_load_performed: false,
        render_performed: false,
        aex_loaded: false,
        worker_started: false,
        broker_load_or_render_allowed: false,
        ofx_route_allowed: false,
        ae_invoked: false,
        private_payload_copied: false,
        fixture_gate_status: None,
        fixture_selected: false,
        fixture_approval_approved: false,
        fixture_loader_enabled: false,
        fixture_real_aex_load_enabled: false,
        fixture_render_png_enabled: false,
        loader_gate_status: None,
        loader_gate_approved: false,
        loader_gate_loader_enabled: false,
        loader_gate_real_aex_load_enabled: false,
        loader_gate_open_candidate_count: 0,
        identity_smoke_status: None,
        identity_smoke_aex_loaded: false,
        identity_smoke_ofx_route_invoked: false,
        identity_smoke_aex_render_correctness_evidence: false,
        ofx_contract_status: None,
        ofx_contract_review_approved: false,
        ofx_contract_ofx_host_may_load_aex: false,
        ofx_contract_ofx_adapter_may_load_aex: false,
        ofx_contract_broker_may_load_aex: false,
        blocked_reason_count: 0,
        input_contains_forbidden_tokens: false,
    }
}

fn native_stage_plan_ready_for_ofx_review(summary: &NativeStagePlanSummary) -> bool {
    summary.provided
        && summary.no_load_stage_plan_ready
        && summary.worker_runtime_evidence_ready
        && (!summary.cleanroom_boundary_provided || summary.cleanroom_boundary_no_loader_or_sdk)
        && summary.selector_execution_blocked
        && summary.render_blocked
        && summary.ofx_route_blocked
        && !summary.input_contains_forbidden_tokens
}

fn loader_slice_review_ready_for_ofx_review(summary: &LoaderSliceReviewSummary) -> bool {
    summary.provided
        && summary.ready_for_manual_loader_slice_review_no_load
        && !summary.loader_slice_approved
        && !summary.loader_enabled
        && !summary.real_aex_load_enabled
        && !summary.native_loader_calls_allowed
        && !summary.broker_may_load_aex
        && !summary.worker_may_load_plugin
        && !summary.render_performed
        && !summary.ofx_route_allowed
        && !summary.input_contains_forbidden_tokens
}

fn loader_approval_ready_for_ofx_review(summary: &LoaderApprovalSummary) -> bool {
    summary.provided
        && summary.validation_status.as_deref()
            == Some("approved_for_loader_implementation_review_no_load")
        && summary.approval_accepted
        && summary.loader_review_approved
        && summary.loader_slice_review_packet_checked
        && summary.loader_slice_review_packet_status.as_deref()
            == Some("ready_for_manual_loader_slice_review_no_load")
        && summary
            .loader_slice_review_packet_checksum_algorithm
            .as_deref()
            == Some("fnv1a64-v1-noncryptographic")
        && !summary.native_load_performed
        && !summary.loader_enabled
        && !summary.real_aex_load_enabled
        && !summary.native_loader_calls_allowed
        && !summary.worker_may_load_plugin
        && !summary.broker_may_load_aex
        && !summary.render_performed
        && !summary.ofx_route_allowed
        && summary.receipt_allows_separate_loader_implementation_review
        && !summary.receipt_allows_native_aex_load
        && !summary.receipt_allows_worker_plugin_load
        && !summary.receipt_allows_render_png
        && !summary.receipt_allows_ofx_route
        && summary.blocked_reason_count == 0
        && !summary.input_contains_forbidden_tokens
}

fn aex_metadata_gate_ready_for_ofx_review(summary: &AexMetadataGateSummary) -> bool {
    summary.provided
        && summary.status.as_deref() == Some("aex_metadata_gate_ready_no_load")
        && summary.report_kind.as_deref() == Some("aex_metadata_gate_integration")
        && summary.publication_status.as_deref() == Some("local-only")
        && summary.ready_for_ofx_review_no_load
        && !summary.native_load_performed
        && !summary.render_performed
        && !summary.aex_loaded
        && !summary.worker_started
        && !summary.broker_load_or_render_allowed
        && !summary.ofx_route_allowed
        && !summary.ae_invoked
        && !summary.private_payload_copied
        && summary.fixture_gate_status.as_deref() == Some("review_queue_not_approved")
        && !summary.fixture_selected
        && !summary.fixture_approval_approved
        && !summary.fixture_loader_enabled
        && !summary.fixture_real_aex_load_enabled
        && !summary.fixture_render_png_enabled
        && summary.loader_gate_status.as_deref() == Some("loader_gate_not_opened")
        && !summary.loader_gate_approved
        && !summary.loader_gate_loader_enabled
        && !summary.loader_gate_real_aex_load_enabled
        && summary.loader_gate_open_candidate_count == 0
        && summary.identity_smoke_status.as_deref() == Some("fixture_identity_smoke_ready_no_load")
        && !summary.identity_smoke_aex_loaded
        && !summary.identity_smoke_ofx_route_invoked
        && !summary.identity_smoke_aex_render_correctness_evidence
        && summary.ofx_contract_status.as_deref() == Some("deferred-contract-only")
        && !summary.ofx_contract_review_approved
        && !summary.ofx_contract_ofx_host_may_load_aex
        && !summary.ofx_contract_ofx_adapter_may_load_aex
        && !summary.ofx_contract_broker_may_load_aex
        && summary.blocked_reason_count == 0
        && !summary.input_contains_forbidden_tokens
}

fn native_stage_runtime_evidence_ready(evidence: &NativeStageRuntimeEvidence) -> bool {
    evidence.worker_identity_revalidation_required.as_deref() == Some("passed")
        && evidence.worker_attestation_required.as_deref() == Some("passed")
        && evidence.sandbox_preflight_required.as_deref() == Some("passed")
        && evidence.job_object_required.as_deref() == Some("assigned-with-kill-on-close")
        && evidence.handle_inheritance_required.as_deref()
            == Some("sentinel_not_inherited-with-explicit-handle-list")
}

fn native_stage_cleanroom_boundary_no_loader_or_sdk(
    boundary: &NativeStageCleanroomBoundary,
) -> bool {
    boundary.native_loader_calls_allowed == Some(false)
        && boundary.adobe_sdk_headers_allowed == Some(false)
        && boundary.abi_generator_allowed == Some(false)
        && boundary.third_party_effect_host_crate_allowed == Some(false)
        && boundary.third_party_pipl_crate_allowed == Some(false)
        && boundary.reuse_existing_aviutl_dynamic_loader_for_aex_allowed == Some(false)
        && boundary.pf_names_are_planning_labels_only == Some(true)
        && boundary.metadata_labels_do_not_define_abi == Some(true)
}

fn non_empty_string(value: String) -> Option<String> {
    if value.is_empty() {
        None
    } else {
        Some(value)
    }
}

fn sanitized_non_empty_string(
    value: String,
    input_contains_forbidden_tokens: bool,
) -> Option<String> {
    if input_contains_forbidden_tokens {
        None
    } else {
        non_empty_string(value)
    }
}

fn string_contains_forbidden_tokens(text: &str) -> bool {
    let text = text.to_ascii_lowercase();
    forbidden_serialized_tokens()
        .iter()
        .any(|token| text.contains(token))
}

fn loader_slice_review_contains_forbidden_tokens(text: &str) -> bool {
    let text = text.to_ascii_lowercase();
    let mut tokens = forbidden_serialized_tokens();
    tokens.extend(loader_slice_review_forbidden_tokens());
    tokens.iter().any(|token| text.contains(token))
}

fn loader_approval_contains_forbidden_tokens(text: &str) -> bool {
    let text = text.to_ascii_lowercase();
    let mut tokens = forbidden_serialized_tokens();
    tokens.extend(loader_slice_review_forbidden_tokens());
    tokens.extend(loader_approval_forbidden_tokens());
    tokens.iter().any(|token| text.contains(token))
}

fn aex_metadata_gate_contains_forbidden_tokens(text: &str) -> bool {
    let text = text.to_ascii_lowercase();
    let mut tokens = forbidden_serialized_tokens();
    tokens.extend(aex_metadata_gate_forbidden_tokens());
    tokens.iter().any(|token| text.contains(token))
}

fn forbidden_serialized_tokens() -> Vec<String> {
    vec![
        "sha256".to_string(),
        "base64".to_string(),
        ["load", "library"].concat(),
        ["lib", "loading"].concat(),
        ["effect", "main"].concat(),
        ["output", "_png"].concat(),
        ["input", "_png"].concat(),
        "rendered_pixels".to_string(),
        "host process started".to_string(),
    ]
}

fn loader_slice_review_forbidden_tokens() -> Vec<String> {
    vec![
        "adaptivefilter.aex".to_string(),
        "medianpro.aex".to_string(),
        "d:\\projects\\01_project\\04_tools\\ae_plugins".to_string(),
        "ae_plugins".to_string(),
    ]
}

fn loader_approval_forbidden_tokens() -> Vec<String> {
    vec![
        ".aex".to_string(),
        "plugin_path".to_string(),
        "normalized_plugin_path".to_string(),
        "worker_exe".to_string(),
        "binary_payload".to_string(),
        "payload_bytes".to_string(),
        "copied_asset".to_string(),
        "native_load_result".to_string(),
        "d:\\".to_string(),
        "d:/".to_string(),
    ]
}

fn aex_metadata_gate_forbidden_tokens() -> Vec<String> {
    vec![
        "adaptivefilter.aex".to_string(),
        "medianpro.aex".to_string(),
        "d:\\projects\\01_project\\04_tools".to_string(),
        "d:/projects/01_project/04_tools".to_string(),
        "ae_plugins".to_string(),
        "plugin_path".to_string(),
        "normalized_plugin_path".to_string(),
        "binary_payload".to_string(),
        "payload_bytes".to_string(),
        "copied_asset".to_string(),
        "native_load_result".to_string(),
    ]
}

type OfxFacadeReadinessCliArgs = (
    PathBuf,
    PathBuf,
    PathBuf,
    Option<PathBuf>,
    Option<PathBuf>,
    Option<PathBuf>,
    Option<PathBuf>,
    Vec<PathBuf>,
    PathBuf,
);

fn parse_args() -> Result<OfxFacadeReadinessCliArgs, String> {
    let mut contract = None;
    let mut fixture_gate = None;
    let mut loader_gate = None;
    let mut native_stage_plan = None;
    let mut loader_slice_review = None;
    let mut loader_approval_report = None;
    let mut aex_metadata_gate_report = None;
    let mut capabilities = Vec::new();
    let mut capability_dir = None;
    let mut out = PathBuf::from("target")
        .join("aex-ofx-facade-readiness")
        .join("ofx-facade.local.json");
    let mut args = std::env::args().skip(1);

    while let Some(arg) = args.next() {
        match arg.as_str() {
            "--contract" => {
                contract = args.next().map(PathBuf::from);
                if contract.is_none() {
                    return Err("--contract requires a JSON path".to_string());
                }
            }
            "--fixture-gate" => {
                fixture_gate = args.next().map(PathBuf::from);
                if fixture_gate.is_none() {
                    return Err("--fixture-gate requires a JSON path".to_string());
                }
            }
            "--loader-gate" => {
                loader_gate = args.next().map(PathBuf::from);
                if loader_gate.is_none() {
                    return Err("--loader-gate requires a JSON path".to_string());
                }
            }
            "--native-stage-plan" => {
                native_stage_plan = args.next().map(PathBuf::from);
                if native_stage_plan.is_none() {
                    return Err("--native-stage-plan requires a JSON path".to_string());
                }
            }
            "--loader-slice-review-packet" => {
                loader_slice_review = args.next().map(PathBuf::from);
                if loader_slice_review.is_none() {
                    return Err("--loader-slice-review-packet requires a JSON path".to_string());
                }
            }
            "--loader-approval-report" => {
                loader_approval_report = args.next().map(PathBuf::from);
                if loader_approval_report.is_none() {
                    return Err("--loader-approval-report requires a JSON path".to_string());
                }
            }
            "--aex-metadata-gate-report" => {
                aex_metadata_gate_report = args.next().map(PathBuf::from);
                if aex_metadata_gate_report.is_none() {
                    return Err("--aex-metadata-gate-report requires a JSON path".to_string());
                }
            }
            "--capability" => {
                let path = args
                    .next()
                    .map(PathBuf::from)
                    .ok_or_else(|| "--capability requires a JSON path".to_string())?;
                capabilities.push(path);
            }
            "--capability-dir" => {
                capability_dir = args.next().map(PathBuf::from);
                if capability_dir.is_none() {
                    return Err("--capability-dir requires a directory".to_string());
                }
            }
            "--out" => {
                out = args
                    .next()
                    .map(PathBuf::from)
                    .ok_or_else(|| "--out requires a JSON path".to_string())?;
            }
            "--help" | "-h" => {
                return Err("usage: ofx_aex_facade_readiness --contract analysis/OFX_AEX_FACADE_CONTRACT_2026-05-31.json --fixture-gate analysis/AEX_FIXTURE_REVIEW_GATE_2026-05-31.json --loader-gate target/aex-probe-readiness/loader-gate.local.json [--native-stage-plan target/aex-native-stage-plan/native-stage-plan.local.json] [--loader-slice-review-packet target/aex-loader-slice-review/loader-slice-review.local.json] [--loader-approval-report target/aex-loader-approval/approval-validation.local.json] [--aex-metadata-gate-report target/aex-metadata-gate-integration/metadata-gate.local.json] [--capability capabilities/effect.capability.json | --capability-dir target/aex-probe-readiness/capabilities] [--out target/aex-ofx-facade-readiness/ofx-facade.local.json]".to_string());
            }
            other => return Err(format!("unknown argument: {other}")),
        }
    }

    if let Some(dir) = capability_dir {
        let mut discovered = std::fs::read_dir(&dir)
            .map_err(|err| format!("failed to read capability dir {}: {err}", dir.display()))?
            .filter_map(|entry| entry.ok().map(|entry| entry.path()))
            .filter(|path| path.extension().and_then(|ext| ext.to_str()) == Some("json"))
            .collect::<Vec<_>>();
        discovered.sort();
        capabilities.extend(discovered);
    }

    Ok((
        contract.ok_or_else(|| "--contract is required".to_string())?,
        fixture_gate.ok_or_else(|| "--fixture-gate is required".to_string())?,
        loader_gate.ok_or_else(|| "--loader-gate is required".to_string())?,
        native_stage_plan,
        loader_slice_review,
        loader_approval_report,
        aex_metadata_gate_report,
        capabilities,
        out,
    ))
}

fn main() -> Result<(), Box<dyn Error>> {
    let (
        contract_path,
        fixture_gate_path,
        loader_gate_path,
        native_stage_plan_path,
        loader_slice_review_path,
        loader_approval_report_path,
        aex_metadata_gate_report_path,
        capability_paths,
        out_path,
    ) = match parse_args() {
        Ok(args) => args,
        Err(message) => {
            eprintln!("{message}");
            std::process::exit(2);
        }
    };
    let contract = std::fs::read_to_string(&contract_path)?;
    let fixture_gate = std::fs::read_to_string(&fixture_gate_path)?;
    let loader_gate = std::fs::read_to_string(&loader_gate_path)?;
    let native_stage_plan = native_stage_plan_path
        .as_ref()
        .map(std::fs::read_to_string)
        .transpose()?;
    let loader_slice_review = loader_slice_review_path
        .as_ref()
        .map(std::fs::read_to_string)
        .transpose()?;
    let loader_approval_report = loader_approval_report_path
        .as_ref()
        .map(std::fs::read_to_string)
        .transpose()?;
    let aex_metadata_gate_report = aex_metadata_gate_report_path
        .as_ref()
        .map(std::fs::read_to_string)
        .transpose()?;
    let capability_texts = capability_paths
        .iter()
        .map(std::fs::read_to_string)
        .collect::<Result<Vec<_>, _>>()?;
    let capability_refs = capability_texts
        .iter()
        .map(String::as_str)
        .collect::<Vec<_>>();
    let report = plan_ofx_facade_readiness_json_with_all_evidence(OfxFacadeReadinessJsonInputs {
        contract_json: &contract,
        fixture_gate_json: &fixture_gate,
        loader_gate_json: &loader_gate,
        native_stage_plan_json: native_stage_plan.as_deref(),
        loader_slice_review_json: loader_slice_review.as_deref(),
        loader_approval_report_json: loader_approval_report.as_deref(),
        aex_metadata_gate_report_json: aex_metadata_gate_report.as_deref(),
        capability_jsons: &capability_refs,
    })?;
    write_ofx_facade_report_create_new(&out_path, &report)?;
    println!("{}", out_path.display());
    Ok(())
}

pub fn validate_ofx_facade_report_output_path(path: &Path) -> Result<(), String> {
    if path_has_traversal(path) {
        return Err("OFX readiness report path must not contain traversal components".to_string());
    }
    if !path_has_extension(path, "json") {
        return Err("OFX readiness report path must have .json extension".to_string());
    }
    if !output_is_under_target_root(path) {
        return Err(
            "OFX readiness report path must be under target/aex-ofx-facade-readiness".to_string(),
        );
    }
    Ok(())
}

pub fn write_ofx_facade_report_create_new(path: &Path, text: &str) -> Result<(), Box<dyn Error>> {
    validate_ofx_facade_report_output_path(path)?;
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    if !output_parent_canonical_is_under_target_root(path) {
        return Err(
            "OFX readiness report parent must resolve under target/aex-ofx-facade-readiness".into(),
        );
    }
    let mut file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(path)
        .map_err(|err| {
            if err.kind() == ErrorKind::AlreadyExists {
                std::io::Error::new(
                    ErrorKind::AlreadyExists,
                    "OFX readiness report already exists",
                )
            } else {
                err
            }
        })?;
    file.write_all(text.as_bytes())?;
    file.write_all(b"\n")?;
    Ok(())
}

fn output_parent_canonical_is_under_target_root(path: &Path) -> bool {
    let Some(parent) = path.parent() else {
        return false;
    };
    let Ok(root) = std::fs::canonicalize(target_root()) else {
        return false;
    };
    let Ok(parent) = std::fs::canonicalize(parent) else {
        return false;
    };
    parent.starts_with(root)
}

fn target_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("target")
        .join("aex-ofx-facade-readiness")
}

fn output_is_under_target_root(path: &Path) -> bool {
    absolute_like(path).starts_with(absolute_like(&target_root()))
}

fn absolute_like(path: &Path) -> PathBuf {
    if path.is_absolute() {
        path.to_path_buf()
    } else {
        Path::new(env!("CARGO_MANIFEST_DIR")).join(path)
    }
}

fn path_has_extension(path: &Path, expected: &str) -> bool {
    path.extension()
        .and_then(|extension| extension.to_str())
        .is_some_and(|extension| extension.eq_ignore_ascii_case(expected))
}

fn path_has_traversal(path: &Path) -> bool {
    path.components().any(|component| {
        matches!(
            component,
            std::path::Component::ParentDir | std::path::Component::CurDir
        )
    })
}
