[package]
name = "aex-guest-worker"
version = "0.1.0"
edition.workspace = true
license = "GPL-2.0-only"

[dependencies]
aex-abi = { path = "../aex-abi" }
goblin.workspace = true
iced-x86.workspace = true
image = { version = "0.25", default-features = false, features = ["png"] }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
unicorn-engine.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "aex-guest-worker"
path = "src/main.rs"
