<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <PlatformToolset>v143</PlatformToolset>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <TreatWarningAsError>false</TreatWarningAsError>
      <DisableSpecificWarnings>4103;4996;%(DisableSpecificWarnings)</DisableSpecificWarnings>
    </ClCompile>
  </ItemDefinitionGroup>
</Project>
