#!/usr/bin/env python3
"""Build a local index of canonical AEX Compat Lab artifacts.

The index reads JSON artifacts only and prefers the real `ae-*`/`scattermap-*`
chain over unit-test generated files. It never opens AEX files or invokes AE/OFX.
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


LAB_ROOT = Path(__file__).resolve().parents[1]
TARGET_ROOT = LAB_ROOT / "target"
INDEX_ROOT = TARGET_ROOT / "artifact-index"

ARTIFACT_SPECS = {
    "static_report": {
        "root": TARGET_ROOT / "aex-static-probe",
        "kind_key": "report_kind",
        "kind": "aex_static_probe",
        "patterns": ["ae-plugins-schema3-*.local.json", "ae-plugins-schema2-*.local.json", "ae-plugins-*.local.json"],
    },
    "pipl_resource_catalog": {
        "root": TARGET_ROOT / "pipl-resource-catalog",
        "kind_key": "report_kind",
        "kind": "aex_pipl_resource_catalog",
        "patterns": ["ae-pipl-resource-catalog-*.local.json"],
    },
    "parameter_schema_plan": {
        "root": TARGET_ROOT / "parameter-schema-plan",
        "kind_key": "report_kind",
        "kind": "aex_parameter_schema_plan",
        "patterns": ["ae-parameter-schema-plan-*.local.json"],
    },
    "parameter_schema_review": {
        "root": TARGET_ROOT / "parameter-schema-review",
        "kind_key": "packet_kind",
        "kind": "aex_parameter_schema_review_packet",
        "patterns": ["ae-parameter-schema-review-*.local.json"],
    },
    "redacted_schema_verifier": {
        "root": TARGET_ROOT / "redacted-schema-verifier",
        "kind_key": "report_kind",
        "kind": "aex_redacted_schema_verifier",
        "patterns": ["ae-redacted-schema-verifier-*.local.json"],
    },
    "synthetic_pipl_parser_selftest": {
        "root": TARGET_ROOT / "synthetic-pipl-parser-selftest",
        "kind_key": "report_kind",
        "kind": "aex_synthetic_pipl_parser_selftest",
        "patterns": ["ae-synthetic-pipl-parser-selftest-*.local.json"],
    },
    "synthetic_pipl_payload_parser": {
        "root": TARGET_ROOT / "synthetic-pipl-payload-parser",
        "kind_key": "report_kind",
        "kind": "aex_synthetic_pipl_payload_parser",
        "patterns": ["ae-synthetic-pipl-payload-parser-*.local.json"],
    },
    "pipl_parser_gate": {
        "root": TARGET_ROOT / "pipl-parser-gate",
        "kind_key": "report_kind",
        "kind": "aex_pipl_parser_gate",
        "patterns": ["ae-pipl-parser-gate-*.local.json"],
    },
    "pipl_resource_consistency_audit": {
        "root": TARGET_ROOT / "pipl-resource-consistency-audit",
        "kind_key": "report_kind",
        "kind": "aex_pipl_resource_consistency_audit",
        "patterns": ["ae-pipl-resource-consistency-audit-*.local.json"],
    },
    "pipl_payload_adapter_review": {
        "root": TARGET_ROOT / "pipl-payload-adapter-review",
        "kind_key": "packet_kind",
        "kind": "aex_pipl_payload_adapter_review_packet",
        "patterns": ["ae-pipl-payload-adapter-review-*.local.json"],
    },
    "aepx_static_probe": {
        "root": TARGET_ROOT / "aepx-static-probe",
        "kind_key": "report_kind",
        "kind": "aepx_static_probe",
        "patterns": ["ae-project-aepx-*.local.json"],
    },
    "aepx_edit_plan": {
        "root": TARGET_ROOT / "aepx-edit-plan",
        "kind_key": "packet_kind",
        "kind": "aepx_edit_plan_packet",
        "patterns": ["ae-project-aepx-edit-plan-*.local.json"],
    },
    "aepx_roundtrip_validator": {
        "root": TARGET_ROOT / "aepx-roundtrip-validator",
        "kind_key": "report_kind",
        "kind": "aepx_roundtrip_validator",
        "patterns": ["ae-project-aepx-roundtrip-validator-*.local.json"],
    },
    "aepx_redacted_text_inventory": {
        "root": TARGET_ROOT / "aepx-redacted-text-inventory",
        "kind_key": "report_kind",
        "kind": "aepx_redacted_text_inventory",
        "patterns": ["ae-project-aepx-redacted-text-inventory-*.local.json"],
    },
    "aepx_redacted_text_classifier": {
        "root": TARGET_ROOT / "aepx-redacted-text-classifier",
        "kind_key": "report_kind",
        "kind": "aepx_redacted_text_classifier",
        "patterns": ["ae-project-aepx-redacted-text-classifier-*.local.json"],
    },
    "candidate_matrix": {
        "root": TARGET_ROOT / "candidate-matrix",
        "kind_key": "report_kind",
        "kind": "aex_candidate_matrix",
        "patterns": ["ae-candidate-matrix-schema3-*.local.json", "ae-candidate-matrix-*.local.json"],
    },
    "dependency_matrix": {
        "root": TARGET_ROOT / "dependency-matrix",
        "kind_key": "report_kind",
        "kind": "aex_dependency_matrix",
        "patterns": ["ae-dependency-matrix-*.local.json"],
    },
    "dependency_preflight": {
        "root": TARGET_ROOT / "dependency-preflight",
        "kind_key": "report_kind",
        "kind": "aex_dependency_availability_preflight",
        "patterns": ["ae-dependency-preflight-*.local.json"],
    },
    "dependency_review": {
        "root": TARGET_ROOT / "dependency-review",
        "kind_key": "packet_kind",
        "kind": "aex_dependency_review_packet",
        "patterns": ["ae-dependency-review-*.local.json"],
    },
    "sandbox_policy": {
        "root": TARGET_ROOT / "sandbox-policy",
        "kind_key": "packet_kind",
        "kind": "aex_sandbox_policy_packet",
        "patterns": ["ae-sandbox-policy-*.local.json"],
    },
    "image_fixture_suite": {
        "root": TARGET_ROOT / "image-fixture-suite",
        "kind_key": "report_kind",
        "kind": "aex_image_fixture_suite",
        "patterns": ["ae-image-fixture-suite-*.local.json"],
    },
    "image_fixture_validation": {
        "root": TARGET_ROOT / "image-fixture-validation",
        "kind_key": "report_kind",
        "kind": "aex_image_fixture_validation",
        "patterns": ["ae-image-fixture-validation-*.local.json"],
    },
    "image_suite_selftest": {
        "root": TARGET_ROOT / "image-suite-selftest",
        "kind_key": "report_kind",
        "kind": "aex_image_suite_worker_selftest",
        "patterns": ["ae-image-suite-selftest-*.local.json"],
    },
    "image_input_smoke": {
        "root": TARGET_ROOT / "image-input-smoke",
        "kind_key": "report_kind",
        "kind": "aex_image_input_smoke_tool",
        "patterns": ["ae-image-input-smoke-*.local.json"],
    },
    "render_validation_contract": {
        "root": TARGET_ROOT / "render-validation-contract",
        "kind_key": "report_kind",
        "kind": "aex_render_validation_contract",
        "patterns": ["ae-render-validation-contract-*.local.json"],
    },
    "fixture_manifest": {
        "root": TARGET_ROOT / "fixture-review",
        "kind_key": "manifest_kind",
        "kind": "aex_fixture_review_manifest",
        "patterns": ["ae-plugins-fixture-review-*.local.json"],
    },
    "fixture_decision": {
        "root": TARGET_ROOT / "fixture-approval",
        "kind_key": "manifest_kind",
        "kind": "aex_fixture_decision_manifest",
        "patterns": ["scattermap-hold-*.local.json"],
    },
    "fixture_dossier": {
        "root": TARGET_ROOT / "fixture-dossier",
        "kind_key": "report_kind",
        "kind": "aex_fixture_review_dossier",
        "patterns": ["scattermap-dossier-*.local.json", "ae-fixture-dossier-*.local.json"],
    },
    "fixture_manual_review_packet": {
        "root": TARGET_ROOT / "fixture-manual-review",
        "kind_key": "report_kind",
        "kind": "aex_fixture_manual_review_packet",
        "patterns": ["ae-fixture-manual-review-*.local.json", "scattermap-manual-review-*.local.json"],
    },
    "fixture_provenance_review": {
        "root": TARGET_ROOT / "fixture-provenance-review",
        "kind_key": "report_kind",
        "kind": "aex_fixture_provenance_review_packet",
        "patterns": ["ae-fixture-provenance-review-*.local.json"],
    },
    "fixture_provenance_answer_template": {
        "root": TARGET_ROOT / "fixture-provenance-answer-template",
        "kind_key": "report_kind",
        "kind": "aex_fixture_provenance_answer_template",
        "patterns": ["ae-fixture-provenance-answer-template-*.local.json"],
    },
    "fixture_provenance_answer_validator_selftest": {
        "root": TARGET_ROOT / "fixture-provenance-answer-validator-selftest",
        "kind_key": "report_kind",
        "kind": "aex_fixture_provenance_answer_validator_selftest",
        "patterns": ["ae-fixture-provenance-answer-validator-selftest-*.local.json"],
    },
    "fixture_approval_verifier": {
        "root": TARGET_ROOT / "fixture-approval-verifier",
        "kind_key": "report_kind",
        "kind": "aex_fixture_approval_verifier",
        "patterns": ["ae-fixture-approval-verifier-*.local.json", "scattermap-approval-verifier-*.local.json"],
    },
    "fixture_approval_request": {
        "root": TARGET_ROOT / "fixture-approval-request",
        "kind_key": "report_kind",
        "kind": "aex_fixture_approval_request_packet",
        "patterns": ["ae-fixture-approval-request-*.local.json", "scattermap-approval-request-*.local.json"],
    },
    "candidate_test_handoff": {
        "root": TARGET_ROOT / "candidate-test-handoff",
        "kind_key": "report_kind",
        "kind": "aex_candidate_test_handoff_packet",
        "patterns": ["ae-candidate-test-handoff-*.local.json", "scattermap-test-handoff-*.local.json"],
    },
    "candidate_test_runner_dryrun": {
        "root": TARGET_ROOT / "candidate-test-runner-dryrun",
        "kind_key": "report_kind",
        "kind": "aex_candidate_no_load_test_runner_dryrun",
        "patterns": ["ae-candidate-test-runner-dryrun-*.local.json", "scattermap-test-runner-dryrun-*.local.json"],
    },
    "candidate_test_runner": {
        "root": TARGET_ROOT / "candidate-test-runner",
        "kind_key": "report_kind",
        "kind": "aex_candidate_no_load_test_runner",
        "patterns": ["ae-candidate-test-runner-*.local.json", "scattermap-test-runner-*.local.json"],
    },
    "candidate_compatibility_card": {
        "root": TARGET_ROOT / "candidate-compat-card",
        "kind_key": "report_kind",
        "kind": "aex_candidate_compatibility_card",
        "patterns": ["ae-candidate-compat-card-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9].local.json"],
    },
    "candidate_image_compat_mock": {
        "root": TARGET_ROOT / "candidate-image-compat-mock",
        "kind_key": "report_kind",
        "kind": "aex_candidate_image_compat_mock",
        "patterns": ["ae-candidate-image-compat-mock-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9].local.json"],
    },
    "candidate_ofx_bridge": {
        "root": TARGET_ROOT / "candidate-ofx-bridge",
        "kind_key": "report_kind",
        "kind": "aex_candidate_ofx_bridge_packet",
        "patterns": ["ae-candidate-ofx-bridge-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9].local.json"],
    },
    "candidate_ofx_host_harness_dryrun": {
        "root": TARGET_ROOT / "candidate-ofx-host-harness-dryrun",
        "kind_key": "report_kind",
        "kind": "aex_candidate_ofx_host_harness_dryrun",
        "patterns": ["ae-candidate-ofx-host-harness-dryrun-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9].local.json"],
    },
    "candidate_ofx_host_harness_selftest": {
        "root": TARGET_ROOT / "candidate-ofx-host-harness-selftest",
        "kind_key": "report_kind",
        "kind": "aex_candidate_ofx_host_harness_selftest",
        "patterns": ["ae-candidate-ofx-host-harness-selftest-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9].local.json"],
    },
    "candidate_ofx_runtime_boundary_contract": {
        "root": TARGET_ROOT / "candidate-ofx-runtime-boundary-contract",
        "kind_key": "report_kind",
        "kind": "aex_candidate_ofx_runtime_boundary_contract",
        "patterns": ["ae-candidate-ofx-runtime-boundary-contract-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9].local.json"],
    },
    "candidate_ofx_runtime_approval_request": {
        "root": TARGET_ROOT / "candidate-ofx-runtime-approval-request",
        "kind_key": "report_kind",
        "kind": "aex_candidate_ofx_runtime_approval_request_packet",
        "patterns": ["ae-candidate-ofx-runtime-approval-request-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9].local.json"],
    },
    "candidate_ofx_runtime_approval_verifier": {
        "root": TARGET_ROOT / "candidate-ofx-runtime-approval-verifier",
        "kind_key": "report_kind",
        "kind": "aex_candidate_ofx_runtime_approval_verifier",
        "patterns": ["ae-candidate-ofx-runtime-approval-verifier-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9].local.json"],
    },
    "candidate_ofx_runtime_prerequisite_audit": {
        "root": TARGET_ROOT / "candidate-ofx-runtime-prerequisite-audit",
        "kind_key": "report_kind",
        "kind": "aex_candidate_ofx_runtime_prerequisite_audit",
        "patterns": ["ae-candidate-ofx-runtime-prerequisite-audit-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9].local.json"],
    },
    "candidate_ofx_host_binary_review_request": {
        "root": TARGET_ROOT / "candidate-ofx-host-binary-review-request",
        "kind_key": "report_kind",
        "kind": "aex_candidate_ofx_host_binary_review_request",
        "patterns": ["ae-candidate-ofx-host-binary-review-request-[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9].local.json"],
    },
    "candidate_dependency_scope": {
        "root": TARGET_ROOT / "candidate-dependency-scope",
        "kind_key": "report_kind",
        "kind": "aex_candidate_dependency_scope_packet",
        "patterns": ["ae-candidate-dependency-scope-*.local.json", "scattermap-dependency-scope-*.local.json"],
    },
    "candidate_load_gate_dryrun": {
        "root": TARGET_ROOT / "candidate-load-gate",
        "kind_key": "report_kind",
        "kind": "aex_candidate_load_gate_dryrun",
        "patterns": ["ae-candidate-load-gate-dryrun-*.local.json", "ae-candidate-load-gate-*.local.json"],
    },
    "worker_design": {
        "root": TARGET_ROOT / "worker-design",
        "kind_key": "packet_kind",
        "kind": "aex_worker_sandbox_design_packet",
        "patterns": ["ae-worker-design-*.local.json"],
    },
    "worker_selftest": {
        "root": TARGET_ROOT / "worker-selftest",
        "kind_key": "report_kind",
        "kind": "aex_no_load_worker_selftest",
        "patterns": ["ae-worker-selftest-*.local.json"],
    },
    "load_gate": {
        "root": TARGET_ROOT / "load-gate",
        "kind_key": "report_kind",
        "kind": "aex_load_gate_check",
        "patterns": ["ae-load-gate-with-hold-*.local.json", "ae-load-gate-*.local.json"],
    },
    "native_loader_stub": {
        "root": TARGET_ROOT / "native-loader-stub",
        "kind_key": "report_kind",
        "kind": "aex_native_loader_stub_report",
        "patterns": ["ae-native-loader-stub-*.local.json"],
    },
    "native_loader_design_contract": {
        "root": TARGET_ROOT / "native-loader-design",
        "kind_key": "report_kind",
        "kind": "aex_native_loader_design_contract",
        "patterns": ["ae-native-loader-design-contract-*.local.json", "ae-native-loader-design-*.local.json"],
    },
    "native_loader_broker_selftest": {
        "root": TARGET_ROOT / "native-loader-broker-selftest",
        "kind_key": "report_kind",
        "kind": "aex_native_loader_broker_selftest",
        "patterns": ["ae-native-loader-broker-selftest-*.local.json", "ae-native-loader-broker-*.local.json"],
    },
    "native_loader_runtime_contract": {
        "root": TARGET_ROOT / "native-loader-runtime-contract",
        "kind_key": "report_kind",
        "kind": "aex_native_loader_runtime_contract",
        "patterns": ["ae-native-loader-runtime-contract-*.local.json", "ae-native-loader-runtime-*.local.json"],
    },
    "native_loader_runtime_selftest": {
        "root": TARGET_ROOT / "native-loader-runtime-selftest",
        "kind_key": "report_kind",
        "kind": "aex_native_loader_runtime_selftest",
        "patterns": ["ae-native-loader-runtime-selftest-*.local.json", "ae-runtime-selftest-*.local.json"],
    },
    "native_loader_path_policy_selftest": {
        "root": TARGET_ROOT / "native-loader-path-policy-selftest",
        "kind_key": "report_kind",
        "kind": "aex_native_loader_path_policy_selftest",
        "patterns": ["ae-native-loader-path-policy-selftest-*.local.json", "ae-path-policy-*.local.json"],
    },
    "ofx_facade": {
        "root": TARGET_ROOT / "ofx-facade",
        "kind_key": "packet_kind",
        "kind": "aex_ofx_facade_deferred_packet",
        "patterns": ["ae-ofx-facade-*.local.json"],
    },
    "ofx_noop_mock": {
        "root": TARGET_ROOT / "ofx-noop-mock",
        "kind_key": "report_kind",
        "kind": "aex_ofx_noop_mock_selftest",
        "patterns": ["ae-ofx-noop-*.local.json"],
    },
    "ofx_suite_selftest": {
        "root": TARGET_ROOT / "ofx-suite-selftest",
        "kind_key": "report_kind",
        "kind": "aex_ofx_suite_noop_selftest",
        "patterns": ["ae-ofx-suite-selftest-*.local.json"],
    },
    "ofx_route_contract": {
        "root": TARGET_ROOT / "ofx-route-contract",
        "kind_key": "report_kind",
        "kind": "aex_ofx_route_contract_probe",
        "patterns": ["ae-ofx-route-contract-*.local.json"],
    },
    "safety_audit": {
        "root": TARGET_ROOT / "safety-audit",
        "kind_key": "report_kind",
        "kind": "aex_no_load_safety_chain_audit",
        "patterns": ["ae-no-load-safety-audit-*.local.json"],
    },
    "publication_boundary": {
        "root": TARGET_ROOT / "publication-boundary",
        "kind_key": "report_kind",
        "kind": "aex_publication_boundary_audit",
        "patterns": ["ae-publication-boundary-*.local.json"],
    },
}

REQUIRED_FIELDS = {
    "static_report": ("entries", "summary"),
    "pipl_resource_catalog": ("catalog_state", "rows", "summary", "payload_policy"),
    "parameter_schema_plan": ("plan_state", "schema_surfaces", "candidate_schema_rows", "blockers"),
    "parameter_schema_review": ("review_state", "parser_review_items", "redaction_policy", "ofx_describe_policy"),
    "redacted_schema_verifier": ("verifier_state", "verifier_checks", "redaction_contract", "blockers"),
    "synthetic_pipl_parser_selftest": ("selftest_state", "parser_contract", "case_results", "blockers"),
    "synthetic_pipl_payload_parser": (
        "synthetic_payload_parser_state",
        "parser_api_contract",
        "parser_case_results",
        "blockers",
    ),
    "pipl_parser_gate": ("gate_state", "parser_input_contract", "parser_gate_checks", "candidate_budget_rows"),
    "pipl_resource_consistency_audit": ("audit_state", "audit_passed", "checks", "summary", "blockers"),
    "pipl_payload_adapter_review": (
        "adapter_review_state",
        "adapter_review_contract",
        "review_items",
        "candidate_review_budget",
        "blockers",
    ),
    "aepx_static_probe": ("root", "summary", "edit_surface"),
    "aepx_edit_plan": ("edit_surfaces", "review_blockers", "write_recommendation"),
    "aepx_roundtrip_validator": ("roundtrip_state", "roundtrip_contract", "source_probe_compare", "roundtrip_compare"),
    "aepx_redacted_text_inventory": ("inventory_state", "inventory_contract", "summary", "redaction_policy"),
    "aepx_redacted_text_classifier": (
        "classifier_state",
        "classifier_contract",
        "classification_rows",
        "summary",
    ),
    "candidate_matrix": ("rows", "summary", "matrix_state"),
    "dependency_matrix": ("dependency_rows", "candidate_rows", "dependency_matrix_state"),
    "dependency_preflight": ("dependency_rows", "preflight_state", "summary"),
    "dependency_review": ("review_items", "review_state", "native_load_recommendation"),
    "sandbox_policy": ("policy_categories", "candidate_policy_rows", "sandbox_policy_state"),
    "image_fixture_suite": ("fixtures", "suite_state", "target_candidate"),
    "image_fixture_validation": ("fixture_results", "validation_state", "summary"),
    "image_suite_selftest": ("fixture_results", "suite_selftest_state", "target_candidate"),
    "image_input_smoke": ("smoke_state", "worker_identity_check", "ofx_identity_check", "route_contract_summary"),
    "render_validation_contract": ("contract_state", "render_contract", "image_validation_contract", "blockers"),
    "fixture_manifest": ("selected_candidates", "hold_candidates"),
    "fixture_decision": ("decision", "approval_state", "candidate_relative_path"),
    "fixture_dossier": ("candidate", "review_items", "load_approval_recommendation"),
    "fixture_manual_review_packet": ("review_packet_state", "decision_summary", "dependency_summary", "load_gate_summary"),
    "fixture_provenance_review": (
        "provenance_review_state",
        "provenance_review_items",
        "review_questions",
        "blockers",
    ),
    "fixture_provenance_answer_template": (
        "template_state",
        "answer_template_entries",
        "answer_schema",
        "blockers",
    ),
    "fixture_provenance_answer_validator_selftest": (
        "validator_selftest_state",
        "answer_validation_contract",
        "synthetic_case_results",
        "blockers",
    ),
    "fixture_approval_verifier": (
        "approval_verifier_state",
        "approval_verifier_ready",
        "current_approval_evaluation",
        "synthetic_approval_checks",
        "required_approval_token_name",
    ),
    "fixture_approval_request": (
        "approval_request_state",
        "approval_request_ready",
        "approval_can_be_issued_now",
        "approval_manifest_created",
        "review_checklist",
        "approval_blockers",
        "forbidden_actions_after_approval",
        "required_approval_token_name",
    ),
    "candidate_test_handoff": (
        "handoff_state",
        "handoff_packet_ready",
        "no_load_test_handoff_ready",
        "native_test_handoff_ready",
        "handoff_checks",
        "handoff_blockers",
        "allowed_no_load_handoff_actions",
        "forbidden_handoff_actions",
    ),
    "candidate_test_runner_dryrun": (
        "runner_dryrun_state",
        "runner_dryrun_ready",
        "dry_run_only",
        "would_execute",
        "execution_performed",
        "no_load_test_plan_ready",
        "planned_tests",
        "blocked_cases",
    ),
    "candidate_test_runner": (
        "runner_state",
        "runner_ready",
        "no_load_execution_performed",
        "native_execution_performed",
        "worker_invoked",
        "ofx_mock_invoked",
        "blocked_load_aex_verified",
        "planned_tests",
        "blocked_cases",
    ),
    "candidate_compatibility_card": (
        "compatibility_card_state",
        "candidate_metadata",
        "no_load_test_card",
        "gate_card",
    ),
    "candidate_image_compat_mock": (
        "mock_state",
        "mock_ready",
        "operation",
        "transform_check",
    ),
    "candidate_ofx_bridge": (
        "bridge_state",
        "bridge_ready",
        "image_surface",
        "ofx_bridge_plan",
        "gate_card",
    ),
    "candidate_ofx_host_harness_dryrun": (
        "harness_dryrun_state",
        "harness_dryrun_ready",
        "planned_cases",
        "allowed_harness_actions",
    ),
    "candidate_ofx_host_harness_selftest": (
        "host_harness_selftest_state",
        "host_harness_selftest_ready",
        "host_harness_kind",
        "synthetic_only",
        "synthetic_contract_checks_performed",
        "case_results",
        "allowed_selftest_actions",
    ),
    "candidate_ofx_runtime_boundary_contract": (
        "candidate_ofx_runtime_boundary_contract_state",
        "contract_state",
        "runtime_boundary_ready",
        "runtime_boundary_plan",
        "host_process_policy",
        "ofx_plugin_binary_policy",
        "required_before_runtime_invocation",
    ),
    "candidate_ofx_runtime_approval_request": (
        "runtime_approval_request_state",
        "runtime_approval_request_ready",
        "runtime_approval_can_be_issued_now",
        "runtime_approval_manifest_created",
        "review_checklist",
        "approval_blockers",
        "blocked_actions_after_request",
    ),
    "candidate_ofx_runtime_approval_verifier": (
        "runtime_approval_verifier_state",
        "runtime_approval_verifier_ready",
        "runtime_approval_verified_not_approved",
        "current_runtime_approval_evaluation",
        "synthetic_runtime_approval_checks",
        "runtime_approval_satisfied",
        "runtime_approval_gate_stays_closed",
        "blocked_actions_after_verification",
        "required_approval_token_name",
    ),
    "candidate_ofx_runtime_prerequisite_audit": (
        "runtime_prerequisite_audit_state",
        "runtime_prerequisite_audit_ready",
        "runtime_invocation_prerequisites_ready",
        "prerequisite_audit_checks",
        "prerequisite_gaps",
        "audit_summary",
        "blocked_actions_after_audit",
        "failed_evidence_count",
    ),
    "candidate_ofx_host_binary_review_request": (
        "ofx_host_binary_review_request_state",
        "ofx_host_binary_review_request_ready",
        "ofx_host_binary_review_ready",
        "ofx_host_binary_review_satisfied",
        "ofx_host_binary_review_can_be_approved_now",
        "ofx_host_binary_review_manifest_created",
        "ofx_host_binary_review_gate_stays_closed",
        "host_binary_review_request_state",
        "host_binary_review_request_ready",
        "host_binary_review_request_created",
        "host_binary_review_can_be_approved_now",
        "host_binary_review_satisfied",
        "host_binary_review_manifest_created",
        "host_binary_review_gate_stays_closed",
        "review_request_kind",
        "review_checklist",
        "review_blockers",
        "host_binary_review_blockers",
        "review_blocker_count",
        "host_binary_review_blocker_count",
        "blocked_actions_after_request",
        "ofx_host_binary_review_path_payload_exported",
        "host_binary_review_path_payload_exported",
    ),
    "candidate_dependency_scope": (
        "candidate_dependency_scope_state",
        "candidate_dependency_summary",
        "global_dependency_summary",
        "scoped_gate_recommendation",
    ),
    "candidate_load_gate_dryrun": (
        "candidate_load_gate_dryrun_state",
        "candidate_scoped_load_gate_dry_run_state",
        "candidate_dependencies_clear",
        "native_load_gate",
        "gates",
    ),
    "worker_design": ("primary_review_candidate", "candidate_design_inputs"),
    "worker_selftest": ("steps", "worker_selftest_passed"),
    "load_gate": ("gate_state", "gates"),
    "native_loader_stub": ("stub_state", "refusal_reasons"),
    "native_loader_design_contract": (
        "native_loader_design_state",
        "contract_state",
        "loader_contract",
        "approval_contract",
        "dependency_gate_contract",
        "phase_plan",
    ),
    "native_loader_broker_selftest": (
        "broker_selftest_state",
        "pathless_broker_ready",
        "blocked_action_checks",
        "steps",
    ),
    "native_loader_runtime_contract": (
        "native_loader_runtime_contract_state",
        "runtime_containment_ready",
        "path_allowlist_state",
        "path_policy",
        "timeout_policy",
        "blocked_actions",
    ),
    "native_loader_runtime_selftest": (
        "runtime_selftest_state",
        "runtime_containment_selftest_passed",
        "normal_exit_case_passed",
        "stderr_capture_passed",
        "timeout_case_passed",
        "child_cleanup_passed",
        "child_cases",
    ),
    "native_loader_path_policy_selftest": (
        "path_policy_selftest_state",
        "path_policy_selftest_passed",
        "candidate_path_string_accepted",
        "absolute_path_rejected",
        "traversal_rejected",
        "non_aex_suffix_rejected",
        "redaction_passed",
        "raw_input_paths_serialized",
        "path_cases",
    ),
    "ofx_facade": ("facade_state", "mapping_plan"),
    "ofx_noop_mock": ("mock_state", "identity_check"),
    "ofx_suite_selftest": ("fixture_results", "ofx_suite_selftest_state", "target_candidate"),
    "ofx_route_contract": ("contract_state", "route_contract", "blockers"),
    "safety_audit": ("audit_passed", "artifacts"),
    "publication_boundary": ("source_safety_audit", "publication_blockers", "redacted_local_summary"),
}

SAFETY_FLAGS = (
    "native_load_enabled",
    "native_load_performed",
    "dll_load_performed",
    "render_performed",
    "ae_invoked",
    "ofx_route_invoked",
    "ofx_runtime_invoked",
    "host_process_launch_enabled",
    "private_payload_copied",
    "aex_file_opened",
    "aepx_file_modified",
    "aep_binary_modified",
    "ae_project_write_performed",
    "ofx_plugin_built",
    "ofx_describe_performed",
    "ofx_render_performed",
    "aex_render_performed",
    "render_validation_performed",
    "ppm_pixel_read_performed",
    "aex_file_hashed",
    "aex_file_copied",
    "pipl_payload_parsed",
    "parameter_schema_emitted",
    "redacted_schema_emitted",
    "real_pipl_payload_parser_enabled",
    "real_pipl_payload_parsed",
    "resource_payload_opened",
    "resource_payload_extracted",
    "raw_payload_serialized",
    "ofx_host_binary_opened",
    "ofx_host_binary_hashed",
    "ofx_host_binary_copied",
    "ofx_host_binary_executed",
    "ofx_plugin_binary_opened",
    "ofx_plugin_binary_hashed",
    "ofx_plugin_binary_copied",
)


def path_has_traversal(path: Path) -> bool:
    return any(part in ("..", ".") for part in path.parts)


def resolve_under_root(path: Path, root: Path, *, must_exist: bool) -> Path:
    if path_has_traversal(path):
        raise ValueError("path must not contain traversal components")
    absolute = path if path.is_absolute() else LAB_ROOT / path
    resolved_root = root.resolve(strict=True)
    resolved = absolute.resolve(strict=must_exist)
    if not resolved.is_relative_to(resolved_root):
        raise ValueError(f"path must stay under {root}")
    return resolved


def validate_output_path(path: Path) -> Path:
    if path.suffix.lower() != ".json":
        raise ValueError("artifact index report must have .json extension")
    INDEX_ROOT.mkdir(parents=True, exist_ok=True)
    resolved = resolve_under_root(path, INDEX_ROOT, must_exist=False)
    resolved.parent.mkdir(parents=True, exist_ok=True)
    if not resolved.parent.resolve(strict=True).is_relative_to(INDEX_ROOT.resolve(strict=True)):
        raise ValueError(f"artifact index parent must stay under {INDEX_ROOT}")
    return resolved


def read_json(path: Path) -> dict[str, Any] | None:
    try:
        with path.open("r", encoding="utf-8") as handle:
            payload = json.load(handle)
    except (OSError, json.JSONDecodeError):
        return None
    return payload if isinstance(payload, dict) else None


def preferred_pattern_rank(path: Path, patterns: list[str]) -> int:
    for index, pattern in enumerate(patterns):
        if path.match(pattern):
            return len(patterns) - index
    return 0


def artifact_state(payload: dict[str, Any]) -> dict[str, Any]:
    keys = (
        "audit_state",
        "boundary_state",
        "catalog_state",
        "payload_policy",
        "plan_state",
        "schema_plan_ready",
        "real_parameter_schema_available",
        "payload_parser_enabled",
        "review_state",
        "parser_design_state",
        "redaction_policy_state",
        "ofx_describe_policy_state",
        "redacted_schema_available",
        "ofx_describe_mapping_ready",
        "verifier_state",
        "verifier_ready",
        "real_redacted_schema_available",
        "synthetic_schema_fixture_used",
        "selftest_state",
        "synthetic_parser_ready",
        "synthetic_payloads_used",
        "synthetic_payload_parser_state",
        "synthetic_payload_parser_ready",
        "synthetic_parser_implemented",
        "synthetic_bounds_harness_reused",
        "synthetic_payload_cases_passed",
        "synthetic_payloads_serialized",
        "real_payload_input_allowed_now",
        "output_metadata_only",
        "real_pipl_payload_parser_enabled",
        "real_pipl_payload_parsed",
        "pipl_payload_parsed",
        "parser_case_count",
        "parser_case_passed_count",
        "parser_case_failed_count",
        "resource_payload_opened",
        "resource_payload_extracted",
        "metadata_budget_ready",
        "gate_ready_for_review",
        "metadata_consistency_ready",
        "adapter_review_state",
        "adapter_review_ready",
        "synthetic_parser_contract_reviewed",
        "metadata_consistency_reviewed",
        "metadata_budget_reviewed",
        "parameter_schema_reviewed",
        "redaction_policy_reviewed",
        "ofx_describe_policy_reviewed",
        "real_payload_adapter_allowed_now",
        "parameter_schema_emission_allowed_now",
        "parameter_schema_emitted",
        "redacted_schema_emitted",
        "review_item_count",
        "blocking_review_item_count",
        "source_chain_valid",
        "catalog_summary_recomputed",
        "catalog_rows_recomputed",
        "gate_budget_rows_recomputed",
        "gate_summary_recomputed",
        "raw_payload_serialized",
        "probe_state",
        "xml_parse_state",
        "edit_readiness_state",
        "edit_plan_state",
        "write_recommendation",
        "roundtrip_state",
        "validator_ready",
        "source_structure_match",
        "roundtrip_structure_match",
        "roundtrip_xml_serialized_to_disk",
        "inventory_state",
        "inventory_ready",
        "source_inventory_state",
        "source_inventory_ready",
        "source_roundtrip_state",
        "source_validator_ready",
        "classifier_state",
        "classifier_ready",
        "source_chain_valid",
        "inventory_rows_classified",
        "row_count_matches_inventory_summary",
        "redacted_text_classification_ready",
        "project_write_recommendation",
        "project_write_ready",
        "project_write_allowed_now",
        "classifier_approves_project_write",
        "schema_write_allowed_now",
        "approved_write_candidate_count",
        "classification_row_count",
        "no_write_row_count",
        "unknown_row_count",
        "raw_text_fields_present",
        "text_payload_hash_exported",
        "value_hashes_emitted",
        "absolute_source_paths_in_inventory_rows",
        "absolute_source_paths_in_classifier_rows",
        "text_payload_exported",
        "bdata_payload_exported",
        "gate_state",
        "approval_state",
        "decision_state",
        "stub_state",
        "facade_state",
        "mock_state",
        "ofx_suite_selftest_state",
        "contract_state",
        "real_route_open",
        "mock_route_ready",
        "real_render_open",
        "no_load_validation_ready",
        "matrix_state",
        "dependency_matrix_state",
        "preflight_state",
        "review_state",
        "native_load_recommendation",
        "sandbox_policy_state",
        "suite_state",
        "validation_state",
        "validation_passed",
        "suite_selftest_state",
        "smoke_state",
        "worker_identity_passed",
        "ofx_identity_passed",
        "dossier_state",
        "load_approval_recommendation",
        "review_packet_state",
        "manual_review_ready",
        "approval_ready",
        "approval_blocker_count",
        "recommended_next_decision",
        "provenance_review_state",
        "provenance_review_ready",
        "manual_review_source_ready",
        "approval_request_source_ready",
        "provenance_status",
        "license_status",
        "safety_review_status",
        "publication_boundary_status",
        "local_fixture_safety_status",
        "review_item_count",
        "blocking_review_item_count",
        "review_question_count",
        "unanswered_review_question_count",
        "native_load_gate_stays_closed",
        "aex_file_hashed",
        "aex_file_copied",
        "template_state",
        "template_ready",
        "answer_template_only",
        "source_provenance_review_ready",
        "answer_template_entry_count",
        "answers_present",
        "answered_question_count",
        "pending_answer_count",
        "all_answers_pending",
        "user_answer_artifact_required",
        "answer_template_approves_fixture",
        "answer_template_approves_publication",
        "answer_template_approves_native_load",
        "validator_selftest_state",
        "validator_ready",
        "source_answer_template_ready",
        "real_user_answer_artifact_consumed",
        "synthetic_user_answers_used",
        "synthetic_payloads_serialized",
        "answer_schema_validated",
        "synthetic_case_count",
        "synthetic_case_passed_count",
        "synthetic_case_failed_count",
        "synthetic_valid_case_count",
        "synthetic_rejected_case_count",
        "answers_validated_for_manual_review",
        "approval_verifier_state",
        "approval_verifier_ready",
        "approval_request_state",
        "approval_request_ready",
        "handoff_state",
        "handoff_packet_ready",
        "no_load_test_handoff_ready",
        "native_test_handoff_ready",
        "native_loader_design_ready",
        "runtime_containment_selftest_passed",
        "synthetic_subprocess_only",
        "normal_exit_case_passed",
        "stderr_capture_passed",
        "timeout_case_passed",
        "child_cleanup_passed",
        "no_load_image_test_ready",
        "image_fixture_validation_state",
        "image_fixture_validation_passed",
        "image_input_smoke_state",
        "no_load_render_contract_ready",
        "no_load_ofx_mock_ready",
        "handoff_blocker_count",
        "runner_dryrun_state",
        "runner_dryrun_ready",
        "dry_run_only",
        "would_execute",
        "execution_performed",
        "no_load_test_plan_ready",
        "native_test_plan_ready",
        "real_render_plan_ready",
        "real_ofx_route_plan_ready",
        "image_fixture_case_count",
        "planned_no_load_case_count",
        "planned_native_case_count",
        "planned_real_render_case_count",
        "planned_real_ofx_route_case_count",
        "blocked_case_count",
        "worker_suite_identity_passed",
        "ofx_suite_identity_passed",
        "image_smoke_identity_passed",
        "render_contract_review_ready",
        "ofx_route_contract_review_ready",
        "runner_state",
        "runner_ready",
        "no_load_execution_performed",
        "native_execution_performed",
        "real_render_execution_performed",
        "real_ofx_route_execution_performed",
        "worker_invoked",
        "ofx_mock_invoked",
        "ofx_runtime_invoked",
        "worker_identity_passed",
        "ofx_noop_identity_passed",
        "blocked_load_aex_verified",
        "executed_worker_case_count",
        "executed_ofx_noop_case_count",
        "executed_worker_lifecycle_case_count",
        "executed_native_case_count",
        "executed_real_render_case_count",
        "executed_real_ofx_route_case_count",
        "compatibility_card_state",
        "compatibility_card_ready",
        "unsafe_exports_present",
        "absolute_ppm_paths_exported",
        "absolute_aex_paths_exported",
        "source_compatibility_card_state",
        "source_compatibility_card_ready",
        "source_native_load_gate",
        "source_native_load_gate_stays_closed",
        "source_real_render_open",
        "source_real_route_open",
        "source_path_acceptance_ready",
        "source_aex_path_acceptance_enabled",
        "source_fixture_approval_satisfied",
        "source_absolute_ppm_paths_exported",
        "source_absolute_aex_paths_exported",
        "mock_ready",
        "operation",
        "transform_check",
        "input_ppm_absolute_path_exported",
        "output_ppm_absolute_path_exported",
        "candidate_image_mock_performed",
        "mock_transform_performed",
        "bridge_state",
        "bridge_ready",
        "candidate_image_mock_available",
        "ofx_closed_route_contract_available",
        "ofx_bridge_packet_created",
        "source_image_mock_state",
        "source_ofx_facade_state",
        "source_ofx_route_contract_state",
        "bridge_allowed_route",
        "mock_route_ready",
        "real_ofx_route_ready",
        "ofx_runtime_invoked",
        "aex_runtime_invoked",
        "ofx_describe_ready",
        "ofx_render_ready",
        "render_equivalence_claim_ready",
        "ofx_bridge_path_payload_exported",
        "harness_dryrun_state",
        "harness_dryrun_ready",
        "dry_run_only",
        "host_harness_kind",
        "planned_case_count",
        "planned_noop_describe_case_count",
        "planned_noop_render_case_count",
        "planned_real_describe_case_count",
        "planned_real_render_case_count",
        "source_bridge_state",
        "source_bridge_allowed_route",
        "source_mock_route_ready",
        "source_real_route_open",
        "source_real_ofx_route_ready",
        "source_ofx_runtime_invoked",
        "source_aex_runtime_invoked",
        "source_ofx_describe_ready",
        "source_ofx_render_ready",
        "source_render_equivalence_claim_ready",
        "host_harness_path_payload_exported",
        "requires_future_runtime_approval",
        "host_harness_selftest_state",
        "host_harness_selftest_ready",
        "synthetic_only",
        "synthetic_contract_checks_performed",
        "synthetic_contract_execution_performed",
        "real_execution_performed",
        "real_harness_execution_performed",
        "dry_run_consumed",
        "planned_cases_verified",
        "source_harness_dryrun_state",
        "source_harness_dryrun_ready",
        "source_dry_run_only",
        "source_would_execute",
        "source_execution_performed",
        "source_host_harness_kind",
        "checked_case_count",
        "checked_noop_describe_case_count",
        "checked_noop_render_case_count",
        "checked_real_describe_case_count",
        "checked_real_render_case_count",
        "case_result_count",
        "case_passed_count",
        "case_failed_count",
        "descriptor_contract_checked",
        "render_identity_contract_checked",
        "synthetic_descriptor_created",
        "synthetic_render_contract_created",
        "candidate_mock_surface_reused",
        "candidate_mock_surface_reused_as_string_only",
        "ppm_pixel_read_performed",
        "candidate_ofx_runtime_boundary_contract_state",
        "candidate_ofx_runtime_boundary_state",
        "runtime_boundary_ready",
        "runtime_boundary_kind",
        "boundary_contract_ready",
        "source_bridge_ready",
        "source_harness_dryrun_state",
        "source_harness_dryrun_ready",
        "source_harness_dryrun_only",
        "source_host_harness_selftest_state",
        "source_host_harness_selftest_ready",
        "source_harness_kind",
        "source_synthetic_only",
        "source_real_harness_execution_performed",
        "source_ppm_pixel_read_performed",
        "source_ofx_route_allowed_route",
        "source_ofx_route_real_route_open",
        "source_ofx_route_mock_route_ready",
        "source_native_runtime_contract_state",
        "source_native_runtime_contract_ready",
        "source_native_runtime_path_acceptance_ready",
        "source_native_runtime_process_isolation_required",
        "source_native_runtime_candidate_dependencies_clear",
        "source_fixture_approval_satisfied",
        "no_load_boundary_contract_created",
        "runtime_boundary_step_count",
        "approval_gate_count",
        "required_runtime_evidence_count",
        "ofx_runtime_allowed_now",
        "ofx_runtime_invocation_ready",
        "ofx_runtime_instantiation_ready",
        "ofx_runtime_instantiation_performed",
        "ofx_binary_build_allowed_now",
        "ofx_binary_built",
        "real_ofx_describe_allowed_now",
        "real_ofx_render_allowed_now",
        "no_op_identity_route_preserved",
        "runtime_boundary_path_payload_exported",
        "ofx_host_path_payload_supplied",
        "ofx_plugin_binary_path_payload_supplied",
        "host_process_launch_enabled",
        "runtime_approval_required_before_invocation",
        "requires_future_fixture_approval",
        "requires_future_render_validation_approval",
        "runtime_approval_request_state",
        "runtime_approval_request_ready",
        "runtime_approval_request_created",
        "runtime_approval_can_be_issued_now",
        "runtime_approval_manifest_created",
        "runtime_approval_gate_stays_closed",
        "approval_request_kind",
        "requires_explicit_user_approval",
        "required_approval_token_name",
        "approval_token_not_stored_in_manifest",
        "approval_only_prepares_runtime_review",
        "source_boundary_contract_state",
        "source_boundary_contract_ready",
        "source_contract_state",
        "source_ofx_runtime_allowed_now",
        "source_ofx_runtime_invocation_ready",
        "source_host_process_launch_enabled",
        "source_path_acceptance_ready",
        "source_real_route_open",
        "source_mock_route_ready",
        "source_ofx_runtime_invoked",
        "source_ppm_pixel_read_performed",
        "source_requires_future_runtime_approval",
        "source_requires_future_fixture_approval",
        "source_requires_future_render_validation_approval",
        "review_checklist_count",
        "approval_blocker_count",
        "runtime_approval_path_payload_exported",
        "runtime_approval_verifier_state",
        "runtime_approval_verifier_ready",
        "runtime_approval_verified_not_approved",
        "source_runtime_approval_request_state",
        "source_runtime_approval_request_ready",
        "current_runtime_approval_valid",
        "runtime_approval_satisfied",
        "runtime_approval_gate_closed",
        "boundary_contract_cross_checked",
        "boundary_contract_matches_request",
        "explicit_runtime_approval_present",
        "request_blockers_clear",
        "runtime_boundary_ready",
        "fixture_approval_satisfied",
        "ofx_host_binary_review_ready",
        "runtime_containment_selftest_ready",
        "schema_and_render_validation_ready",
        "path_acceptance_closed",
        "synthetic_runtime_approval_checks_passed",
        "runtime_approval_verifier_path_payload_exported",
        "runtime_prerequisite_audit_state",
        "runtime_prerequisite_audit_ready",
        "runtime_prerequisites_complete",
        "runtime_prerequisites_all_satisfied",
        "runtime_invocation_prerequisites_ready",
        "approval_can_be_issued_now",
        "failed_evidence_count",
        "blocking_prerequisite_count",
        "runtime_prerequisite_count",
        "runtime_prerequisite_satisfied_count",
        "runtime_prerequisite_blocker_count",
        "runtime_approval_gate_stays_closed",
        "runtime_approval_verified_not_approved",
        "runtime_approval_satisfied",
        "runtime_containment_contract_ready",
        "runtime_containment_selftest_synthetic_passed",
        "runtime_containment_selftest_passed",
        "runtime_selftest_state",
        "synthetic_subprocess_only",
        "normal_exit_case_passed",
        "stderr_capture_passed",
        "timeout_case_passed",
        "child_cleanup_passed",
        "parameter_schema_review_policy_ready",
        "parameter_schema_review_state",
        "payload_parser_enabled",
        "redacted_schema_available",
        "ofx_describe_mapping_ready",
        "render_validation_contract_ready",
        "render_validation_contract_state",
        "no_load_validation_ready",
        "real_render_open",
        "ofx_route_contract_closed",
        "runtime_prerequisite_audit_path_payload_exported",
        "ofx_host_binary_review_request_state",
        "ofx_host_binary_review_request_ready",
        "ofx_host_binary_review_satisfied",
        "ofx_host_binary_review_can_be_approved_now",
        "ofx_host_binary_review_manifest_created",
        "ofx_host_binary_review_gate_stays_closed",
        "host_binary_review_request_state",
        "host_binary_review_request_ready",
        "host_binary_review_request_created",
        "host_binary_review_can_be_approved_now",
        "host_binary_review_ready",
        "host_binary_review_satisfied",
        "host_binary_review_manifest_created",
        "host_binary_review_gate_stays_closed",
        "requires_explicit_host_binary_review",
        "host_binary_path_acceptance_ready",
        "host_binary_path_payload_exported",
        "host_binary_review_path_payload_exported",
        "runtime_invocation_prerequisites_ready",
        "accepted_ofx_host_path",
        "accepted_ofx_plugin_binary_path",
        "source_prerequisite_audit_state",
        "source_failed_evidence_count",
        "source_blocking_prerequisite_count",
        "source_runtime_invocation_prerequisites_ready",
        "source_ofx_host_binary_review_ready",
        "source_runtime_containment_selftest_synthetic_passed",
        "source_schema_and_render_validation_ready",
        "source_harness_dryrun_state",
        "source_harness_dryrun_ready",
        "source_host_harness_selftest_state",
        "source_host_harness_selftest_ready",
        "source_boundary_contract_state",
        "source_boundary_contract_ready",
        "source_boundary_host_process_launch_enabled",
        "source_boundary_ofx_host_path_payload_supplied",
        "source_boundary_ofx_plugin_binary_path_payload_supplied",
        "review_checklist_count",
        "review_blocker_count",
        "host_binary_review_blocker_count",
        "ready_no_load_evidence_count",
        "source_no_load_evidence_count",
        "manual_review_required",
        "explicit_user_review_required",
        "approval_only_prepares_host_binary_review",
        "review_does_not_accept_paths",
        "review_does_not_launch_host",
        "review_does_not_invoke_runtime",
        "ofx_host_binary_review_path_payload_exported",
        "approval_can_be_issued_now",
        "approval_manifest_created",
        "requires_explicit_user_approval",
        "current_fixture_approval_valid",
        "approval_gate_stays_closed",
        "manual_review_approval_ready",
        "path_policy_closed",
        "candidate_load_gate_closed",
        "synthetic_approval_checks_passed",
        "required_approval_token_name",
        "approval_token_not_stored_in_manifest",
        "approval_only_prepares_next_gate",
        "candidate_dependency_scope_state",
        "candidate_scope_ready",
        "candidate_dependency_blockers_present",
        "candidate_dependency_blocker_count",
        "candidate_dependency_review_count",
        "candidate_dependency_missing_or_api_set_review_count",
        "candidate_dependency_found_paths_exported",
        "global_dependency_blockers_present",
        "global_dependency_blockers_apply_to_candidate",
        "scoped_gate_recommendation",
        "candidate_load_gate_dryrun_state",
        "candidate_scoped_load_gate_dry_run_state",
        "candidate_gate_ready_for_separate_loader_design",
        "native_load_gate",
        "fixture_approval_satisfied",
        "fixture_decision_manifest_kind",
        "fixture_decision_state",
        "fixture_approval_state",
        "fixture_manual_review_ready",
        "fixture_manual_review_approval_ready",
        "candidate_dependencies_clear",
        "source_load_gate_state",
        "source_load_gate_dependency_recommendation",
        "worker_selftest_passed",
        "native_loader_design_state",
        "loader_design_ready",
        "accepts_aex_path",
        "accepted_aex_path",
        "controller_loads_aex",
        "approval_required_before_aex_path",
        "runtime_approval_required_before_load",
        "separate_process_required",
        "candidate_load_gate_state",
        "source_candidate_load_gate_state",
        "source_stub_state",
        "source_sandbox_policy_state",
        "source_render_contract_state",
        "source_ofx_route_contract_state",
        "broker_selftest_state",
        "pathless_broker_ready",
        "native_loader_design_ready",
        "path_payload_supplied",
        "blocked_action_count",
        "native_loader_runtime_contract_state",
        "runtime_containment_ready",
        "path_allowlist_state",
        "path_acceptance_ready",
        "aex_path_acceptance_enabled",
        "broker_selftest_passed",
        "process_isolation_required",
        "source_native_loader_design_state",
        "source_broker_selftest_state",
        "source_sandbox_policy_state",
        "source_candidate_load_gate_state",
        "source_candidate_scoped_load_gate_state",
        "runtime_selftest_state",
        "runtime_containment_selftest_passed",
        "source_native_loader_runtime_contract_state",
        "synthetic_subprocess_only",
        "normal_exit_case_passed",
        "stderr_capture_passed",
        "timeout_case_passed",
        "child_cleanup_passed",
        "path_policy_selftest_state",
        "path_policy_selftest_passed",
        "source_runtime_selftest_state",
        "source_runtime_selftest_passed",
        "synthetic_path_inputs_only",
        "candidate_path_string_accepted",
        "absolute_path_rejected",
        "traversal_rejected",
        "non_aex_suffix_rejected",
        "redaction_passed",
        "raw_input_paths_serialized",
        "path_case_count",
        "audit_passed",
        "publishable_now",
    )
    return {key: payload.get(key) for key in keys if key in payload}


def artifact_completeness_score(label: str, payload: dict[str, Any]) -> int:
    return sum(1 for field in REQUIRED_FIELDS.get(label, ()) if field in payload)


def safety_summary(payload: dict[str, Any]) -> dict[str, Any]:
    return {flag: payload.get(flag) for flag in SAFETY_FLAGS if flag in payload}


def find_candidates(label: str) -> list[dict[str, Any]]:
    spec = ARTIFACT_SPECS[label]
    root: Path = spec["root"]
    if not root.exists():
        return []
    candidates: list[dict[str, Any]] = []
    for path in root.glob("*.json"):
        payload = read_json(path)
        if payload is None:
            continue
        kind_matches = payload.get(spec["kind_key"]) == spec["kind"]
        if not kind_matches:
            continue
        pattern_rank = preferred_pattern_rank(path, spec["patterns"])
        candidates.append(
            {
                "path": path,
                "payload": payload,
                "pattern_rank": pattern_rank,
                "completeness_score": artifact_completeness_score(label, payload),
                "mtime": path.stat().st_mtime,
            }
        )
    candidates.sort(key=lambda item: (item["pattern_rank"], item["completeness_score"], item["mtime"]), reverse=True)
    return candidates


def select_artifact(label: str) -> dict[str, Any]:
    candidates = find_candidates(label)
    if not candidates:
        return {
            "label": label,
            "found": False,
            "path": None,
            "candidate_count": 0,
            "kind": ARTIFACT_SPECS[label]["kind"],
            "states": {},
            "safety_flags": {},
            "selection_reason": "missing",
        }
    selected = candidates[0]
    payload = selected["payload"]
    return {
        "label": label,
        "found": True,
        "path": str(selected["path"].resolve()),
        "candidate_count": len(candidates),
        "kind": payload.get(ARTIFACT_SPECS[label]["kind_key"]),
        "states": artifact_state(payload),
        "safety_flags": safety_summary(payload),
        "completeness_score": selected["completeness_score"],
        "selection_reason": "preferred_pattern" if selected["pattern_rank"] else "latest_matching_kind",
    }


def index_errors(selected: list[dict[str, Any]]) -> list[str]:
    errors: list[str] = []
    for item in selected:
        if not item["found"]:
            errors.append(f"{item['label']} artifact is missing")
        for flag, value in item.get("safety_flags", {}).items():
            if value is not False:
                errors.append(f"{item['label']} {flag} must be false")
    by_label = {item["label"]: item for item in selected}
    if by_label.get("safety_audit", {}).get("states", {}).get("audit_passed") is not True:
        errors.append("safety_audit audit_passed must be true")
    if by_label.get("publication_boundary", {}).get("states", {}).get("publishable_now") is not False:
        errors.append("publication_boundary publishable_now must be false")
    return errors


def build_index() -> dict[str, Any]:
    selected = [select_artifact(label) for label in ARTIFACT_SPECS]
    errors = index_errors(selected)
    return {
        "schema_version": 1,
        "publication_status": "local-only",
        "report_kind": "aex_artifact_index",
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "index_state": "canonical_chain_indexed" if not errors else "canonical_chain_incomplete",
        "artifact_count": len(selected),
        "found_count": sum(1 for item in selected if item["found"]),
        "artifacts": selected,
        "errors": errors,
        "native_load_enabled": False,
        "native_load_performed": False,
        "dll_load_performed": False,
        "render_performed": False,
        "ae_invoked": False,
        "ofx_route_invoked": False,
        "private_payload_copied": False,
        "aex_file_opened": False,
        "notes": [
            "Index reads JSON artifacts only.",
            "Preferred real-run artifacts are selected by kind and ae/scattermap filename patterns.",
            "No AEX, AE, OFX, image runtime, or binary-payload operation is performed.",
        ],
    }


def write_json_create_new(path: Path, payload: dict[str, Any]) -> Path:
    resolved = validate_output_path(path)
    with resolved.open("x", encoding="utf-8", newline="\n") as handle:
        json.dump(payload, handle, ensure_ascii=False, indent=2)
        handle.write("\n")
    return resolved


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build local AEX Compat Lab artifact index")
    parser.add_argument("--out", required=True, help="Create-new artifact index under target/artifact-index")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    index = build_index()
    written = write_json_create_new(Path(args.out), index)
    print(written)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
