#!/usr/bin/env python3
"""Generate and verify the desktop harness third-party license bundle."""

from __future__ import annotations

import argparse
import hashlib
import html
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "broker" / "crates" / "harness" / "Cargo.toml"
CONFIG = ROOT / "broker" / "about.toml"
LOCKFILE = ROOT / "broker" / "Cargo.lock"
SNAPSHOT = ROOT / "broker" / "licenses" / "third-party-licenses.json"
OUTPUT = ROOT / "THIRD_PARTY_LICENSES.html"
TEXT_OUTPUT = ROOT / "THIRD_PARTY_LICENSES.txt"
CARGO_ABOUT_VERSION = "0.9.1"
TARGETS = (
    "x86_64-pc-windows-msvc",
    "aarch64-apple-darwin",
    "x86_64-apple-darwin",
)
PACKAGE_LINE = re.compile(r"^([^ ]+) v([^ ]+)(?: \(|$)")


def run(arguments: list[str]) -> str:
    return subprocess.run(
        arguments,
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
        encoding="utf-8",
    ).stdout


def external_package(package: dict[str, object]) -> bool:
    source = package.get("source")
    return isinstance(source, str) and bool(source)


def lockfile_sha256() -> str:
    # Hash the lockfile as text, not as the bytes a particular checkout holds:
    # with core.autocrlf=true the working copy carries CRLF and the same
    # committed lockfile hashes differently from an LF checkout, which turned
    # this audit into a verdict about the machine's git configuration.
    normalized = LOCKFILE.read_bytes().replace(b"\r\n", b"\n")
    return hashlib.sha256(normalized).hexdigest()


def compact_cargo_about(raw: dict[str, object]) -> dict[str, object]:
    packages = []
    for entry in raw["crates"]:
        package = entry["package"]
        if not external_package(package):
            continue
        packages.append(
            {
                "name": package["name"],
                "version": package["version"],
                "source": package["source"],
                "license": package["license"],
                "repository": package.get("repository"),
            }
        )
    packages.sort(
        key=lambda package: (package["name"], package["version"], package["source"])
    )

    licenses = []
    for license_entry in raw["licenses"]:
        used_by = []
        for use in license_entry["used_by"]:
            package = use["crate"]
            if external_package(package):
                used_by.append([package["name"], package["version"]])
        if not used_by:
            continue
        used_by.sort()
        licenses.append(
            {
                "name": license_entry["name"],
                "text": "\n".join(
                    line.rstrip()
                    for line in license_entry["text"].replace("\r\n", "\n").split("\n")
                ).rstrip()
                + "\n",
                "used_by": used_by,
            }
        )
    licenses.sort(key=lambda item: (item["name"], item["used_by"], item["text"]))
    return {
        "schema_version": 1,
        "cargo_about_version": CARGO_ABOUT_VERSION,
        "cargo_lock_sha256": lockfile_sha256(),
        "targets": list(TARGETS),
        "packages": packages,
        "licenses": licenses,
    }


def render(snapshot: dict[str, object]) -> str:
    lines = [
        "<!-- Generated by tools/generate-third-party-licenses.py. Do not edit. -->",
        "<!doctype html>",
        '<html lang="en">',
        "<head>",
        '  <meta charset="utf-8">',
        '  <meta name="viewport" content="width=device-width, initial-scale=1">',
        "  <title>AEXCompat Third-Party Licenses</title>",
        "  <style>",
        "    body { font-family: sans-serif; line-height: 1.45; margin: 2rem auto; max-width: 72rem; padding: 0 1rem; }",
        "    pre { border: 1px solid #8888; max-height: 24rem; overflow: auto; padding: 1rem; white-space: pre-wrap; }",
        "  </style>",
        "</head>",
        "<body>",
        "  <h1>AEXCompat Third-Party Licenses</h1>",
        "  <p>License notices for external Cargo packages linked into the AEXCompat desktop harness on supported Windows and macOS targets.</p>",
        "  <p>AEXCompat itself is licensed separately under MPL-2.0; see <code>LICENSE</code>.</p>",
    ]
    for license_entry in snapshot["licenses"]:
        lines.extend(
            [
                "  <section>",
                f"    <h2>{html.escape(license_entry['name'])}</h2>",
                "    <p>Used by:</p>",
                "    <ul>",
            ]
        )
        for name, version in license_entry["used_by"]:
            lines.append(f"      <li>{html.escape(name)} {html.escape(version)}</li>")
        lines.extend(
            [
                "    </ul>",
                f"    <pre>{html.escape(license_entry['text'])}</pre>",
                "  </section>",
            ]
        )
    lines.extend(["</body>", "</html>", ""])
    return "\n".join(lines)


def render_text(snapshot: dict[str, object]) -> str:
    lines = [
        "AEXCompat Third-Party Licenses",
        "================================",
        "",
        "License notices for external Cargo packages linked into the AEXCompat desktop harness on supported Windows and macOS targets.",
        "AEXCompat itself is licensed separately under MPL-2.0; see LICENSE.",
        "",
    ]
    for license_entry in snapshot["licenses"]:
        lines.extend(
            [license_entry["name"], "-" * len(license_entry["name"]), "Used by:"]
        )
        lines.extend(
            f"  - {name} {version}" for name, version in license_entry["used_by"]
        )
        lines.extend(["", license_entry["text"].rstrip(), ""])
    return "\n".join(lines).rstrip() + "\n"


def cargo_tree_packages() -> set[tuple[str, str]]:
    packages: set[tuple[str, str]] = set()
    for target in TARGETS:
        output = run(
            [
                "cargo",
                "tree",
                "--manifest-path",
                str(MANIFEST),
                "--locked",
                "--target",
                target,
                "--edges",
                "normal,build",
                "--prefix",
                "none",
                "--format",
                "{p}",
            ]
        )
        for line in output.splitlines():
            match = PACKAGE_LINE.match(line)
            if not match or match.group(1).startswith("aexcompat-"):
                continue
            packages.add((match.group(1), match.group(2)))
    return packages


def snapshot_packages(snapshot: dict[str, object]) -> set[tuple[str, str]]:
    return {(package["name"], package["version"]) for package in snapshot["packages"]}


def generated_snapshot() -> dict[str, object]:
    version = run(["cargo", "about", "--version"]).strip()
    if version != f"cargo-about {CARGO_ABOUT_VERSION}":
        raise SystemExit(f"expected cargo-about {CARGO_ABOUT_VERSION}, got {version!r}")
    with tempfile.NamedTemporaryFile(suffix=".json", delete=False) as temporary:
        temporary_path = Path(temporary.name)
    try:
        run(
            [
                "cargo",
                "about",
                "generate",
                "--manifest-path",
                str(MANIFEST),
                "--config",
                str(CONFIG),
                "--locked",
                "--fail",
                "--format",
                "json",
                "--output-file",
                str(temporary_path),
            ]
        )
        raw = json.loads(temporary_path.read_text(encoding="utf-8"))
    finally:
        temporary_path.unlink(missing_ok=True)
    return compact_cargo_about(raw)


def refresh() -> None:
    snapshot = generated_snapshot()
    SNAPSHOT.parent.mkdir(parents=True, exist_ok=True)
    SNAPSHOT.write_text(
        json.dumps(snapshot, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )
    OUTPUT.write_text(render(snapshot), encoding="utf-8")
    TEXT_OUTPUT.write_text(render_text(snapshot), encoding="utf-8")


def check() -> None:
    snapshot = json.loads(SNAPSHOT.read_text(encoding="utf-8"))
    regenerated = generated_snapshot()
    if snapshot != regenerated:
        raise SystemExit(
            "third-party license snapshot differs from cargo-about output for the locked harness graph"
        )
    expected = snapshot_packages(snapshot)
    actual = cargo_tree_packages()
    if expected != actual:
        missing = sorted(actual - expected)
        stale = sorted(expected - actual)
        raise SystemExit(
            f"third-party license package drift: missing={missing} stale={stale}"
        )
    rendered = render(snapshot)
    committed = OUTPUT.read_text(encoding="utf-8")
    if rendered != committed:
        raise SystemExit(
            "THIRD_PARTY_LICENSES.html is not generated from the locked snapshot"
        )
    text_rendered = render_text(snapshot)
    text_committed = TEXT_OUTPUT.read_text(encoding="utf-8")
    if text_rendered != text_committed:
        raise SystemExit(
            "THIRD_PARTY_LICENSES.txt is not generated from the locked snapshot"
        )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--refresh", action="store_true")
    args = parser.parse_args()
    if args.refresh:
        refresh()
    else:
        check()
    return 0


if __name__ == "__main__":
    sys.exit(main())
