[CmdletBinding()]
param(
    [switch]$SkipBuild,
    [string]$BuildRoot = ''
)

# Regenerates the broker worker trust constants (runtime admission state) from
# locally built worker binaries. This is required after any worker rebuild;
# broker dispatch fails closed on a worker hash mismatch. It intentionally does
# not touch analysis/ evidence documents; see docs/EVIDENCE_POLICY_2026-07-18.md.

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
if (-not $BuildRoot) { $BuildRoot = Join-Path $repoRoot 'target\minihost-build' }
$trustRoot = Join-Path $repoRoot 'broker\crates\broker\src'

$workers = @(
    @{ Name = 'aex_l2_worker'; Constant = 'L2_WORKER_TRUST'; File = 'generated_l2_worker_trust.rs' },
    @{ Name = 'aex_render_worker'; Constant = 'RENDER_WORKER_TRUST'; File = 'generated_render_worker_trust.rs' },
    @{ Name = 'aex_smart_worker'; Constant = 'SMART_WORKER_TRUST'; File = 'generated_smart_worker_trust.rs' }
)

if (-not $SkipBuild) {
    $cmake = & "$PSScriptRoot\resolve-build-cmake.ps1" '' 'Ninja'
    if (-not $env:INCLUDE) {
        $vsRoot = & "$PSScriptRoot\resolve-msvc-tools.ps1" ''
        $vcvars = Join-Path $vsRoot 'VC\Auxiliary\Build\vcvars64.bat'
        cmd.exe /d /c "`"$vcvars`" >nul && set" | ForEach-Object {
            if ($_ -match '^([^=]+)=(.*)$') { Set-Item -LiteralPath "Env:$($matches[1])" -Value $matches[2] }
        }
    }
    & $cmake '-S' (Join-Path $repoRoot 'minihost') '-B' $BuildRoot '-G' 'Ninja' '-DCMAKE_BUILD_TYPE=Release'
    if ($LASTEXITCODE -ne 0) { throw "cmake configure failed with exit code $LASTEXITCODE" }
    & $cmake '--build' $BuildRoot '--target' 'aex_l2_worker' 'aex_render_worker' 'aex_smart_worker'
    if ($LASTEXITCODE -ne 0) { throw "cmake build failed with exit code $LASTEXITCODE" }
}

foreach ($worker in $workers) {
    $exe = Join-Path $BuildRoot "$($worker.Name).exe"
    if (-not (Test-Path -LiteralPath $exe -PathType Leaf)) {
        throw "Worker binary not found: $exe (build first, or drop -SkipBuild)"
    }
    $item = Get-Item -LiteralPath $exe
    $sha256 = (Get-FileHash -LiteralPath $item.FullName -Algorithm SHA256).Hash.ToLowerInvariant()
    $hashBytes = [regex]::Matches($sha256, '..') | ForEach-Object { '0x' + $_.Value }
    $rows = for ($offset = 0; $offset -lt 32; $offset += 8) {
        '        ' + (($hashBytes[$offset..($offset + 7)] -join ', ') + ',')
    }
    $size = $item.Length.ToString('N0', [Globalization.CultureInfo]::InvariantCulture).Replace(',', '_')
    $trust = @(
        '// Generated by tools/refresh-worker-trust.ps1 or tools/refresh-sdk-grabba-evidence.ps1. Do not edit by hand.'
        "const $($worker.Constant): WorkerTrust = WorkerTrust {"
        '    expected_sha256: ['
        $rows
        '    ],'
        "    expected_size: $size ,"
        '};'
    ) -join "`n"
    $path = Join-Path $trustRoot $worker.File
    [IO.File]::WriteAllText($path, $trust + "`n", [Text.UTF8Encoding]::new($false))
    Write-Output "$($worker.Constant): $sha256 ($($item.Length) bytes) -> $($worker.File)"
}
