[CmdletBinding()]
param(
    [switch]$SkipBuild,
    [string]$BuildRoot = '',
    [string]$TrustRoot = ''
)

# Regenerates the broker worker trust constants (runtime admission state) from
# locally built worker binaries. This is required after any worker rebuild;
# broker dispatch fails closed on a worker hash mismatch. It intentionally does
# not touch analysis/ evidence documents; see docs/EVIDENCE_POLICY_2026-07-18.md.
# All three binaries are hashed before any trust file is written, so a missing
# or unreadable worker leaves every trust constant unchanged.

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
if (-not $BuildRoot) { $BuildRoot = Join-Path $repoRoot 'target\minihost-build' }
if (-not $TrustRoot) { $TrustRoot = Join-Path $repoRoot 'broker\crates\broker\src' }

# L2 trust is also regenerated by the L2 evidence chain refresh; the render and
# smart constants have no other generator.
$workers = @(
    @{ Name = 'aex_l2_worker'; Constant = 'L2_WORKER_TRUST'; File = 'generated_l2_worker_trust.rs';
       Header = '// Generated by tools/refresh-worker-trust.ps1 or tools/refresh-sdk-grabba-evidence.ps1. Do not edit by hand.' },
    @{ Name = 'aex_render_worker'; Constant = 'RENDER_WORKER_TRUST'; File = 'generated_render_worker_trust.rs';
       Header = '// Generated by tools/refresh-worker-trust.ps1. Do not edit by hand.' },
    @{ Name = 'aex_smart_worker'; Constant = 'SMART_WORKER_TRUST'; File = 'generated_smart_worker_trust.rs';
       Header = '// Generated by tools/refresh-worker-trust.ps1. Do not edit by hand.' }
)

if (-not $SkipBuild) {
    $cmake = & "$PSScriptRoot\resolve-build-cmake.ps1" '' 'Ninja'
    if (-not $env:INCLUDE) {
        $vsRoot = & "$PSScriptRoot\resolve-msvc-tools.ps1" ''
        $vcvars = Join-Path $vsRoot 'VC\Auxiliary\Build\vcvars64.bat'
        cmd.exe /d /c "`"$vcvars`" >nul && set" | ForEach-Object {
            if ($_ -match '^([^=]+)=(.*)$') { Set-Item -LiteralPath "Env:$($matches[1])" -Value $matches[2] }
        }
    }
    & $cmake '-S' (Join-Path $repoRoot 'minihost') '-B' $BuildRoot '-G' 'Ninja' '-DCMAKE_BUILD_TYPE=Release'
    if ($LASTEXITCODE -ne 0) { throw "cmake configure failed with exit code $LASTEXITCODE" }
    & $cmake '--build' $BuildRoot '--target' 'aex_l2_worker' 'aex_render_worker' 'aex_smart_worker'
    if ($LASTEXITCODE -ne 0) { throw "cmake build failed with exit code $LASTEXITCODE" }
}

# Pass 1: verify and hash every worker binary before touching any trust file.
$pending = foreach ($worker in $workers) {
    $exe = Join-Path $BuildRoot "$($worker.Name).exe"
    if (-not (Test-Path -LiteralPath $exe -PathType Leaf)) {
        throw "Worker binary not found: $exe (build first, or drop -SkipBuild)"
    }
    $item = Get-Item -LiteralPath $exe
    $sha256 = (Get-FileHash -LiteralPath $item.FullName -Algorithm SHA256).Hash.ToLowerInvariant()
    $hashBytes = [regex]::Matches($sha256, '..') | ForEach-Object { '0x' + $_.Value }
    $rows = for ($offset = 0; $offset -lt 32; $offset += 8) {
        '        ' + (($hashBytes[$offset..($offset + 7)] -join ', ') + ',')
    }
    $size = $item.Length.ToString('N0', [Globalization.CultureInfo]::InvariantCulture).Replace(',', '_')
    $trust = @(
        $worker.Header
        "const $($worker.Constant): WorkerTrust = WorkerTrust {"
        '    expected_sha256: ['
        $rows
        '    ],'
        "    expected_size: $size ,"
        '};'
    ) -join "`n"
    @{
        Constant = $worker.Constant
        File = $worker.File
        Path = Join-Path $TrustRoot $worker.File
        Content = $trust + "`n"
        Sha256 = $sha256
        Size = $item.Length
    }
}

# Pass 2: every binary verified; write all trust files together.
foreach ($entry in $pending) {
    [IO.File]::WriteAllText($entry.Path, $entry.Content, [Text.UTF8Encoding]::new($false))
    Write-Output "$($entry.Constant): $($entry.Sha256) ($($entry.Size) bytes) -> $($entry.File)"
}
