[CmdletBinding()]
param(
    [string]$SdkRoot = $env:AFTER_EFFECTS_SDK_ROOT,
    [switch]$SkipBuild
)

$ErrorActionPreference = 'Stop'
$SdkRoot = & "$PSScriptRoot\resolve-after-effects-sdk.ps1" $SdkRoot
$repoRoot = Split-Path -Parent $PSScriptRoot
$worker = Join-Path $repoRoot 'target\minihost-build\aex_l2_worker.exe'
$trustSource = Join-Path $repoRoot 'broker\crates\broker\src\generated_l2_worker_trust.rs'
$harness = Join-Path $repoRoot 'broker\target\debug\aexcompat-harness.exe'
$grabba = Join-Path $repoRoot 'target\sdk-fixtures\grabba\Grabba.aex'
$reportRoot = Join-Path $repoRoot 'target\final-integration-evidence'
$evidencePath = Join-Path $repoRoot 'analysis\SDK_GRABBA_AEGP_RUNTIME_RESULT_2026-07-16.json'
$cmake = & "$PSScriptRoot\resolve-build-cmake.ps1" '' 'Ninja'
if (-not $env:INCLUDE) {
    $vsRoot = & "$PSScriptRoot\resolve-msvc-tools.ps1" ''
    $vcvars = Join-Path $vsRoot 'VC\Auxiliary\Build\vcvars64.bat'
    cmd.exe /d /c "`"$vcvars`" >nul && set" | ForEach-Object {
        if ($_ -match '^([^=]+)=(.*)$') { Set-Item -LiteralPath "Env:$($matches[1])" -Value $matches[2] }
    }
}

function Get-Identity([string]$Path) {
    $item = Get-Item -LiteralPath $Path
    $rootPrefix = $repoRoot.TrimEnd('\') + '\'
    if (-not $item.FullName.StartsWith($rootPrefix, [StringComparison]::OrdinalIgnoreCase)) {
        throw "Evidence artifact is outside the repository: $($item.FullName)"
    }
    [ordered]@{
        path = $item.FullName.Substring($rootPrefix.Length).Replace('\', '/')
        size_bytes = $item.Length
        sha256 = (Get-FileHash -LiteralPath $item.FullName -Algorithm SHA256).Hash.ToLowerInvariant()
    }
}

function Invoke-Checked([string]$Command, [string[]]$Arguments) {
    $previousErrorAction = $ErrorActionPreference
    $ErrorActionPreference = 'Continue'
    & $Command @Arguments
    $exitCode = $LASTEXITCODE
    $ErrorActionPreference = $previousErrorAction
    if ($exitCode -ne 0) {
        throw "$Command failed with exit code $exitCode"
    }
}

if (-not $SkipBuild) {
    Invoke-Checked $cmake @('-S', (Join-Path $repoRoot 'minihost'), '-B', (Join-Path $repoRoot 'target\minihost-build'), '-G', 'Ninja', '-DCMAKE_BUILD_TYPE=Release')
    Invoke-Checked $cmake @('--build', (Join-Path $repoRoot 'target\minihost-build'), '--target', 'aex_l2_worker')
}
$workerIdentity = Get-Identity $worker
if (-not $SkipBuild) {
    $hashBytes = [regex]::Matches($workerIdentity.sha256, '..') | ForEach-Object { '0x' + $_.Value }
    $rows = for ($offset = 0; $offset -lt 32; $offset += 8) {
        '        ' + (($hashBytes[$offset..($offset + 7)] -join ', ') + ',')
    }
    $trust = @(
        '// Generated by tools/refresh-worker-trust.ps1 or tools/refresh-sdk-grabba-evidence.ps1. Do not edit by hand.'
        'const L2_WORKER_TRUST: WorkerTrust = WorkerTrust {'
        '    expected_sha256: ['
        $rows
        '    ],'
        "    expected_size: $($workerIdentity.size_bytes.ToString('N0', [Globalization.CultureInfo]::InvariantCulture).Replace(',', '_')) ,"
        '};'
    ) -join "`n"
    [IO.File]::WriteAllText($trustSource, $trust + "`n", [Text.UTF8Encoding]::new($false))

    & (Join-Path $PSScriptRoot 'build-sdk-grabba.ps1') -SdkRoot $SdkRoot
    if ($LASTEXITCODE -ne 0) { throw "Grabba build failed with exit code $LASTEXITCODE" }
    Invoke-Checked cargo @('build', '--manifest-path', (Join-Path $repoRoot 'broker\Cargo.toml'), '-p', 'aexcompat-harness')
} else {
    foreach ($artifact in @($worker, $harness, $grabba)) {
        if (-not (Test-Path -LiteralPath $artifact -PathType Leaf)) {
            throw "SkipBuild requires an existing artifact: $artifact"
        }
    }
}

New-Item -ItemType Directory -Force -Path $reportRoot | Out-Null
$routes = [ordered]@{
    initialization = '--initialize-experimental-aegp'
    update_menu = '--dispatch-experimental-aegp-update-menu'
    idle = '--dispatch-experimental-aegp-idle'
    command_roundtrip = '--dispatch-experimental-aegp-command-roundtrip'
}
$reports = [ordered]@{}
foreach ($entry in $routes.GetEnumerator()) {
    $output = & $harness $entry.Value $grabba 2>&1
    $exitCode = $LASTEXITCODE
    if ($exitCode -ne 0) { throw "$($entry.Key) dispatch failed: $output" }
    $report = ($output -join "`n") | ConvertFrom-Json
    $report | Add-Member -NotePropertyName exit_code -NotePropertyValue $exitCode -Force
    $report | Add-Member -NotePropertyName module_audit_status -NotePropertyValue $report.module_audit.status -Force
    $report | Add-Member -NotePropertyName module_audit_phase_count -NotePropertyValue $report.module_audit.phase_count -Force
    $report | Add-Member -NotePropertyName module_audit_unknown_count -NotePropertyValue $report.module_audit.unknown_count -Force
    $auditPhases = [ordered]@{}
    foreach ($phase in @('post_load', 'pre_unload', 'observed_union')) {
        $auditPhases[$phase] = [ordered]@{ status = $report.module_audit.$phase.status; unknown_count = $report.module_audit.$phase.unknown_count }
    }
    $report | Add-Member -NotePropertyName module_audit_phases -NotePropertyValue $auditPhases -Force
    if ($entry.Key -eq 'update_menu') {
        $report | Add-Member -NotePropertyName compatibility_boundary -NotePropertyValue 'SDK-derived AEGP Item Suite acquisition version 10 exposes legacy GetActiveItem and GetItemType while unsupported slots remain fail-closed.' -Force
    }
    $reportPath = Join-Path $reportRoot "grabba-$($entry.Key.Replace('_', '-')).json"
    [IO.File]::WriteAllText($reportPath, ($report | ConvertTo-Json -Depth 20) + "`n", [Text.UTF8Encoding]::new($false))
    $reports[$entry.Key] = $report
}

$existing = Get-Content -LiteralPath $evidencePath -Raw | ConvertFrom-Json
$existing.recorded_at = (Get-Date).ToString('yyyy-MM-ddTHH:mm:ssK')
$existing.source_provenance.git_head = (git -C $repoRoot rev-parse HEAD).Trim()
$existing.source_provenance.worktree_was_dirty = [bool](git -C $repoRoot status --porcelain)
$sourceFiles = @('minihost/src/l2_main.cpp', 'broker/crates/broker/src/image_render.rs', 'broker/crates/broker/src/generated_l2_worker_trust.rs')
$existing.source_provenance.files = @($sourceFiles | ForEach-Object { Get-Identity (Join-Path $repoRoot $_) })
$existing.initialization.report = $reports.initialization
$existing.initialization.exit_code = 0
foreach ($name in @('update_menu', 'idle', 'command_roundtrip')) {
    $existing.$name = $reports[$name]
}
$artifactMap = @{
    official_sdk_grabba_fixture = Get-Identity $grabba
    aegp_worker = $workerIdentity
    command_harness = Get-Identity $harness
}
foreach ($record in $existing.authenticated_artifacts) {
    $identity = $artifactMap[$record.role]
    $record.path = $identity.path
    $record.size_bytes = $identity.size_bytes
    if ($record.role -ne 'official_sdk_grabba_fixture') { $record.sha256 = $identity.sha256 }
}
$reportNames = @{
    initialization = 'grabba-initialization.json'
    update_menu = 'grabba-update-menu.json'
    idle = 'grabba-idle.json'
    command_roundtrip = 'grabba-command-roundtrip.json'
}
$existing.authenticated_reports = @($reportNames.GetEnumerator() | ForEach-Object {
    $identity = Get-Identity (Join-Path $reportRoot $_.Value)
    [ordered]@{ route = $_.Key; path = $identity.path; size_bytes = $identity.size_bytes; sha256 = $identity.sha256 }
})
foreach ($record in $existing.production_artifact_snapshot) {
    $identity = Get-Identity (Join-Path $repoRoot $record.path)
    $record.size_bytes = $identity.size_bytes
    $record.sha256 = $identity.sha256
}
[IO.File]::WriteAllText($evidencePath, ($existing | ConvertTo-Json -Depth 30) + "`n", [Text.UTF8Encoding]::new($false))
Write-Output "Approved Release L2 worker: $($workerIdentity.sha256) ($($workerIdentity.size_bytes) bytes)"
